.TH "hmmfetch" 1 "@RELEASEDATE@" "@PACKAGE@ @RELEASE@" "@PACKAGE@ Manual"

.SH NAME
.TP 
hmmfetch - retrieve an HMM from an HMM database

.SH SYNOPSIS
.B hmmfetch
.I [options]
.I database
.I name

.SH DESCRIPTION

.B hmmfetch
is a small utility that retrieves an HMM called
.I name
from a HMMER model database called
.I database.
in a new format, 
and prints that model to standard output.
For example,
.I hmmfetch Pfam rrm
retrieves the RRM (RNA recognition motif) model from
Pfam, if the environment variable HMMERDB is
set to the location of the Pfam database.
The retrieved HMM file is written in HMMER 2 ASCII format.

.PP
The database must have an associated GSI index file.
To index an HMM database, use the program
.B hmmindex.

.SH OPTIONS

.TP
.B -h
Print brief help; includes version number and summary of
all options, including expert options.

.TP
.B -n
Interpret
.I name
as an HMM number instead of a name. Numbering starts at 0.
For example, to fetch the first HMM from an HMM database
called
.B foo,
you would do 
.B hmmfetch -n 0 foo.

