#! /bin/sh

pkg=$1

echo Building $pkg...
./rootbuild wrasse    /tmp $pkg intel-linux   --with-pvm CFLAGS=-O2        > build-intel-linux.log &
./rootbuild whippet   /tmp $pkg hp-hpux       none       CFLAGS=-O         > build-hp-hpux.log &
./rootbuild warhorse  /tmp $pkg sgi-irix64    none       CC=cc,CFLAGS=-O2  > build-sgi-irix64.log &  
./rootbuild warlord   /tmp $pkg sun-solaris   none       CFLAGS=-O2        > build-sun-solaris.log &
#./rootbuild warlock   /tmp $pkg ibm-aix       none       CFLAGS=-O         > build-ibm-aix.log &
./rootbuild waterbug  /tmp $pkg alpha-tru64   none       CC=cc,CFLAGS=-O   > build-alpha-tru64.log &
./rootbuild warhawk   /tmp $pkg intel-freebsd none       CFLAGS=-O2        > build-intel-freebsd.log &
#./rootbuild wonderboy /tmp $pkg intel-openbsd none       CFLAGS=-O2        > build-intel-openbsd.log &
./rootbuild whipworm  /tmp $pkg intel-solaris none       CFLAGS=-O2        > build-intel-solaris.log &


