#! /bin/sh

pkg=$1

echo Building $pkg...
./rootbuild wrasse    /tmp $pkg intel-linux   --with-pvm CFLAGS=-O2
./rootbuild whippet   /tmp $pkg hp-hpux       none       CFLAGS=-O
./rootbuild warhorse  /tmp $pkg sgi-irix64    none       CC=cc,CFLAGS=-O2
./rootbuild warlord   /tmp $pkg sun-solaris   none       CFLAGS=-O2
./rootbuild warlock   /tmp $pkg ibm-aix       none       CFLAGS=-O
./rootbuild waterbug  /tmp $pkg alpha-tru64   none       CC=cc,CFLAGS=-O
./rootbuild warhawk   /tmp $pkg intel-freebsd none       CFLAGS=-O2
./rootbuild wonderboy /tmp $pkg intel-openbsd none       CFLAGS=-O2
./rootbuild whipworm  /tmp $pkg intel-solaris none       CFLAGS=-O2


