#! /usr/local/bin/perl

$pkg = shift;

system "./rootbuild wrasse    /tmp $pkg intel-linux   --with-pvm CFLAGS=-O2";
system "./rootbuild whippet   /tmp $pkg hp-hpux       \"\"       CFLAGS=-O";
system "./rootbuild warhorse  /tmp $pkg sgi-irix64    \"\"       \"CC=cc CFLAGS=-O2\"";
system "./rootbuild warlord   /tmp $pkg sun-solaris   \"\"       CFLAGS=-O2";
system "./rootbuild warlock   /tmp $pkg ibm-aix       \"\"       CFLAGS=-O";
system "./rootbuild waterbug  /tmp $pkg alpha-tru64   \"\"       \"CC=cc CFLAGS=-O\"";
system "./rootbuild warhawk   /tmp $pkg intel-freebsd \"\"       CFLAGS=-O2";
system "./rootbuild wonderboy /tmp $pkg intel-openbsd \"\"       CFLAGS=-O2";
system "./rootbuild whipworm  /tmp $pkg intel-solaris \"\"       CFLAGS=-O2";


