#! /usr/local/bin/perl

$node       = shift;
$arena      = shift;
$pkg        = shift;
$platform   = shift;
$configopts = shift;
$makeopts   = shift;

print "pkg        = $pkg\n";
print "node       = $node\n";
print "arena      = $arena\n";
print "platform   = $platform\n";
print "configopts = $configopts\n";
print "makeopts   = $makeopts\n";

print "Copying files...            \t";
system "scp nodebuild $node:$arena/";
if ($? != 0) { die "copy failed" };
system "scp $pkg.tar.gz $node:$arena/";
if ($? != 0) { die "copy failed" };
print "[done]\n";

print "Running nodebuild...        \t";
print "ssh $node $arena/nodebuild $arena $pkg $platform $configopts $makeopts\n";
system "ssh $node $arena/nodebuild $arena $pkg $platform $configopts $makeopts";

if ($? != 0) { die "nodebuild failed" };
print "[done]\n";

print "Getting the tarball back... \t";
system "scp $node:$arena/$pkg.bin.$platform.tar.gz .";
if ($? != 0) { die "scp failed" };
print "[done]\n";

print "Cleaning up...              \t";
system "ssh $node \"\rm -f $arena/nodebuild\"";
if ($? != 0) { die "rm -f failed" };
system "ssh $node \"\rm -f $arena/$pkg.bin.$platform.tar.gz\"";
if ($? != 0) { die "rm -f failed" };
print "[done]\n";

exit 0;
	
