MODULE = utilities

PROGS =  alimask    \
	 hmmconvert \
	 hmmfetch   \
	 hmmlogo    \
	 hmmstat 

LIBOBJS = 

LIBHDRS = 

OBJS =

HDRS =

UTESTS = 

STATS  = 

BENCHMARKS = 

EXAMPLES =

LIBTMP =

top_srcdir   = ../..
top_builddir = ../..
srcdir       = .

SHELL        = /bin/sh

include ../Makefile-subdirs.mk

################################################################
# @LICENSE@
#
# SVN $URL$
# SVN $Id$
################################################################

