/* version.h -- automatically generated by a Makefile. DO NOT EDIT. */
#define PACKAGE     "HMMER"
#define RELEASE     "2.2c"
#define RELEASEDATE "June 2001"
#define COPYRIGHT   "Copyright (C) 1992-2001 HHMI/Washington University School of Medicine"
#define LICENSE     "Freely distributed under the GNU General Public License (GPL)"
