.TH "hmmfetch" 1 @RELEASEDATE@ "HMMER @RELEASE@" "HMMER Manual"

.SH NAME
.TP 
hmmfetch - retrieve an HMM from an HMM database

.SH SYNOPSIS
.B hmmfetch
.I [options]
.I database
.I name

.SH DESCRIPTION

.B hmmfetch
is a small utility that retrieves an HMM called
.I name
from a HMMER model database called
.I database.
in a new format, 
and prints that model to standard output.
For example,
.I hmmfetch Pfam rrm
retrieves the RRM (RNA recognition motif) model from
Pfam, if the environment variable HMMERDB is
set to the location of the Pfam database.
The retrieved HMM file is written in HMMER 2 ASCII format.

.PP
The database must have an associated GSI index file.
To index an HMM database, use the program
.B hmmindex.

.SH OPTIONS

.TP
.B -h
Print brief help; includes version number and summary of
all options, including expert options.

.SH SEE ALSO

.PP
@SEEALSO@
.PP
User guide and tutorial: Userguide.ps
.PP
WWW: 
.B http://hmmer.wustl.edu/

.SH AUTHOR

This software and documentation is Copyright (C) 1992-1998 Washington
University School of Medicine.  It is freely distributable under terms
of the GNU General Public License. See COPYING in the source code
distribution for more details, or contact me.

.nf
Sean Eddy
Dept. of Genetics
Washington Univ. School of Medicine
4566 Scott Ave.
St Louis, MO 63110 USA
Phone: 1-314-362-7666
FAX  : 1-314-362-7855
Email: eddy@genetics.wustl.edu
.fi


