/* SSE implementation of Forward/Backward "parsers".
 *
 * These are O(M+L) linear memory Forward/Backward implementations
 * that keep only one row of DP memory for the main states, and one
 * column 0..L of DP memory for the special states B,E,N,C,J. This
 * allows us to do posterior decoding on the special states and
 * determine regions of the target sequence that are generated by the
 * nonhomology states (NCJ) versus not -- thus, identifying where
 * high-probability "regions" are, the first step of identifying the
 * domain structure of a target sequence.
 * 
 * These were originally motivated by the need to replace generic
 * Forward/Backward calculations in hit postprocessing, both because
 * they are too slow, and because they are O(NM) memory.
 * 
 * Contents:
 *   1. Parser implementations.
 *   2. Benchmark driver.
 *   3. Unit tests.
 *   4. Test driver.
 *   5. Example.
 *   6. Copyright and license information.
 * 
 * SRE, Thu Jul 31 08:43:20 2008 [Janelia]
 * SVN $Id$
 */
#include "p7_config.h"

#include <stdio.h>
#include <math.h>

#include <xmmintrin.h>		/* SSE  */
#include <emmintrin.h>		/* SSE2 */

#include "easel.h"
#include "esl_sse.h"

#include "hmmer.h"
#include "impl_sse.h"

/*****************************************************************
 * 1. Parser implementations
 *****************************************************************/

/* Function:  p7_ForwardParser()
 * Synopsis:  Calculates Forward score and X columns in O(M+L) memory.
 * Incept:    SRE, Thu Jul 31 09:30:31 2008 [Janelia]
 *
 * Purpose:   Calculates the Forward score and X columns for sequence
 *            <dsq> of length <L> residues, using optimized profile
 *            <om>, and a preallocated DP matrix <ox>, in linear
 *            memory $O(M+L)$. Return the Forward score (in nats) in
 *            <ret_sc>, and <ox->xmx[][0,1..L]> contain the DP matrix
 *            in single-precision probability for all special X states
 *            (BENCJ).
 *            
 *            The caller must provide a suitably allocated <ox>, with
 *            one DP row to fit <om->M> states, and X beams to fit <L>
 *            residues: for instance by calling <ox = p7_omx_Create(M, 0,
 *            L)> or <p7_omx_GrowTo(ox, M, 0, L)>.
 *            
 *            The Forward score may overflow -- and will, on
 *            high-scoring sequences. Range is limited to -88 to +88
 *            nats (-127 to 127 bits). Scores will not underflow, for
 *            models configured in local mode, within HMMER's design
 *            limits ($L \leq 10^5$; $M \leq 10^4$). On overflow,
 *            <*ret_sc> is <eslINFINITY>.
 *            
 *            The model must be in a local mode; other modes cannot
 *            guarantee that we will not underflow.
 *
 * Args:      dsq     - digital target sequence, 1..L
 *            L       - length of dsq in residues          
 *            om      - optimized profile
 *            ox      - DP matrix
 *            ret_sc  - RETURN: Forward score (in nats)          
 *
 * Returns:   <eslOK> on success; 
 *            <eslERANGE> if the score overflows the limited range of
 *            a probability-space odds ratio; in this case, this is
 *            a high-scoring hit of score > ~128 bits.
 *
 * Throws:    <eslEINVAL> if <ox> allocation is too small, or if the profile
 *            isn't in local alignment mode.
 */
int
p7_ForwardParser(const ESL_DSQ *dsq, int L, const P7_OPROFILE *om, P7_OMX *ox, float *ret_sc)
{
  register __m128 mpv, dpv, ipv;   /* previous row values                                       */
  register __m128 sv;		   /* temp storage of 1 curr row value in progress              */
  register __m128 dcv;		   /* delayed storage of D(i,q+1)                               */
  register __m128 xEv;		   /* E state: keeps max for Mk->E as we go                     */
  register __m128 xBv;		   /* B state: splatted vector of B[i-1] for B->Mk calculations */
  __m128   zerov;		   /* splatted 0.0's in a vector                                */
  float    xN, xE, xB, xC, xJ;	   /* special states' scores                                    */
  int i;			   /* counter over sequence positions 1..L                      */
  int q;			   /* counter over quads 0..nq-1                                */
  int j;			   /* counter over DD iterations (4 is full serialization)      */
  int Q       = p7O_NQF(om->M);	   /* segment length: # of vectors                              */
  __m128 *dp  = ox->dpf[0];        /* using {MDI}MX(q) macro requires initialization of <dp>    */
  __m128 *rp;			   /* will point at om->rf[x] for residue x[i]                  */
  __m128 *tp;			   /* will point into (and step thru) om->tf                    */

  /* Check that the DP matrix is ok for us. */
  if (Q > ox->allocQ4)                                 ESL_EXCEPTION(eslEINVAL, "DP matrix allocated too small");
  if (ox->allocXRQ*4 <= L)                             ESL_EXCEPTION(eslEINVAL, "DP matrix X beams allocated too small");
  if (om->mode != p7_LOCAL && om->mode != p7_UNILOCAL) ESL_EXCEPTION(eslEINVAL, "Fast filter only works for local alignment");
  ox->M  = om->M;
  ox->L  = L;

  /* Initialization.
   */
  zerov = _mm_setzero_ps();
  for (q = 0; q < Q; q++)
    MMXo(q) = IMXo(q) = DMXo(q) = zerov;
  xE    = ox->xmx[p7X_E][0] = 0.;
  xN    = ox->xmx[p7X_N][0] = 1.;
  xJ    = ox->xmx[p7X_J][0] = 0.;
  xB    = ox->xmx[p7X_B][0] = om->xf[p7O_N][p7O_MOVE];
  xC    = ox->xmx[p7X_C][0] = 0.;

#if p7_DEBUGGING
  if (ox->debugging) p7_omx_DumpFloatRow(ox, TRUE, 0, 9, 5, xE, xN, xJ, xB, xC);	/* logify=TRUE, <rowi>=0, width=8, precision=5*/
#endif

  for (i = 1; i <= L; i++)
    {
      rp    = om->rf[dsq[i]];
      tp    = om->tf;
      dcv   = _mm_setzero_ps();
      xEv   = _mm_setzero_ps();
      xBv   = _mm_set1_ps(xB);

      /* Right shifts by 4 bytes. 4,8,12,x becomes x,4,8,12.  Shift zeros on.
       */
      mpv = MMXo(Q-1);  mpv = _mm_shuffle_ps(mpv, mpv, _MM_SHUFFLE(2, 1, 0, 0));   mpv = _mm_move_ss(mpv, zerov);
      dpv = DMXo(Q-1);  dpv = _mm_shuffle_ps(dpv, dpv, _MM_SHUFFLE(2, 1, 0, 0));   dpv = _mm_move_ss(dpv, zerov);
      ipv = IMXo(Q-1);  ipv = _mm_shuffle_ps(ipv, ipv, _MM_SHUFFLE(2, 1, 0, 0));   ipv = _mm_move_ss(ipv, zerov);
      
      for (q = 0; q < Q; q++)
	{
	  /* Calculate new MMXo(i,q); don't store it yet, hold it in sv. */
	  sv   =                _mm_mul_ps(xBv, *tp);  tp++;
	  sv   = _mm_add_ps(sv, _mm_mul_ps(mpv, *tp)); tp++;
	  sv   = _mm_add_ps(sv, _mm_mul_ps(ipv, *tp)); tp++;
	  sv   = _mm_add_ps(sv, _mm_mul_ps(dpv, *tp)); tp++;
	  sv   = _mm_mul_ps(sv, *rp);                  rp++;
	  xEv  = _mm_add_ps(xEv, sv);
	  
	  /* Load {MDI}(i-1,q) into mpv, dpv, ipv;
	   * {MDI}MX(q) is then the current, not the prev row
	   */
	  mpv = MMXo(q);
	  dpv = DMXo(q);
	  ipv = IMXo(q);

	  /* Do the delayed stores of {MD}(i,q) now that memory is usable */
	  MMXo(q) = sv;
	  DMXo(q) = dcv;

	  /* Calculate the next D(i,q+1) partially: M->D only;
           * delay storage, holding it in dcv
	   */
	  dcv   = _mm_mul_ps(sv, *tp); tp++;

	  /* Calculate and store I(i,q) */
	  sv     =                _mm_mul_ps(mpv, *tp);  tp++;
	  sv     = _mm_add_ps(sv, _mm_mul_ps(ipv, *tp)); tp++;
	  IMXo(q) = _mm_mul_ps(sv, *rp);                  rp++;
	}	  

      /* Now the DD paths. We would rather not serialize them but 
       * in an accurate Forward calculation, we have few options.
       */
      /* dcv has carried through from end of q loop above; store it 
       * in first pass, we add M->D and D->D path into DMX
       */
      /* We're almost certainly're obligated to do at least one complete 
       * DD path to be sure: 
       */
      dcv    = _mm_shuffle_ps(dcv, dcv, _MM_SHUFFLE(2, 1, 0, 0));
      dcv    = _mm_move_ss(dcv, zerov);
      DMXo(0) = zerov;
      tp     = om->tf + 7*Q;	/* set tp to start of the DD's */
      for (q = 0; q < Q; q++) 
	{
	  DMXo(q) = _mm_add_ps(dcv, DMXo(q));	
	  dcv    = _mm_mul_ps(DMXo(q), *tp); tp++; /* extend DMXo(q), so we include M->D and D->D paths */
	}

      /* now. on small models, it seems best (empirically) to just go
       * ahead and serialize. on large models, we can do a bit better,
       * by testing for when dcv (DD path) accrued to DMXo(q) is below
       * machine epsilon for all q, in which case we know DMXo(q) are all
       * at their final values. The tradeoff point is (empirically) somewhere around M=100,
       * at least on my desktop. We don't worry about the conditional here;
       * it's outside any inner loops.
       */
      if (om->M < 100)
	{			/* Fully serialized version */
	  for (j = 1; j < 4; j++)
	    {
	      dcv = _mm_shuffle_ps(dcv, dcv, _MM_SHUFFLE(2, 1, 0, 0));
	      dcv = _mm_move_ss(dcv, zerov);
	      tp = om->tf + 7*Q;	/* set tp to start of the DD's */
	      for (q = 0; q < Q; q++) 
		{
		  DMXo(q) = _mm_add_ps(dcv, DMXo(q));	
		  dcv    = _mm_mul_ps(dcv, *tp);   tp++; /* note, extend dcv, not DMXo(q); only adding DD paths now */
		}	    
	    }
	} 
      else
	{			/* Slightly parallelized version, but which incurs some overhead */
	  for (j = 1; j < 4; j++)
	    {
	      register __m128 cv;	/* keeps track of whether any DD's change DMXo(q) */

	      dcv = _mm_shuffle_ps(dcv, dcv, _MM_SHUFFLE(2, 1, 0, 0));
	      dcv = _mm_move_ss(dcv, zerov);
	      tp  = om->tf + 7*Q;	/* set tp to start of the DD's */
	      cv  = zerov;
	      for (q = 0; q < Q; q++) 
		{
		  sv     = _mm_add_ps(dcv, DMXo(q));	
		  cv     = _mm_or_ps(cv, _mm_cmpgt_ps(sv, DMXo(q))); /* remember if DD paths changed any DMXo(q): *without* conditional branch */
		  DMXo(q) = sv;	                                    /* store new DMXo(q) */
		  dcv    = _mm_mul_ps(dcv, *tp);   tp++;            /* note, extend dcv, not DMXo(q); only adding DD paths now */
		}	    
	      if (! _mm_movemask_ps(cv)) break; /* DD's didn't change any DMXo(q)? Then we're done, break out. */
	    }
	}

      /* Add D's to xEv */
      for (q = 0; q < Q; q++) xEv = _mm_add_ps(DMXo(q), xEv);

      /* Finally the "special" states, which start from Mk->E (->C, ->J->B) */
      /* The following incantation is a horizontal sum of xEv's elements  */
      /* These must follow DD calculations, because D's contribute to E in Forward
       * (as opposed to Viterbi)
       */
      xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(0, 3, 2, 1)));
      xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(1, 0, 3, 2)));
      _mm_store_ss(&xE, xEv);

      xN =  xN * om->xf[p7O_N][p7O_LOOP];
      xC = (xC * om->xf[p7O_C][p7O_LOOP]) +  (xE * om->xf[p7O_E][p7O_MOVE]);
      xJ = (xJ * om->xf[p7O_J][p7O_LOOP]) +  (xE * om->xf[p7O_E][p7O_LOOP]);
      xB = (xJ * om->xf[p7O_J][p7O_MOVE]) +  (xN * om->xf[p7O_N][p7O_MOVE]);
      /* and now xB will carry over into next i, and xC carries over after i=L */

      ox->xmx[p7X_E][i] = xE;
      ox->xmx[p7X_N][i] = xN;
      ox->xmx[p7X_J][i] = xJ;
      ox->xmx[p7X_B][i] = xB;
      ox->xmx[p7X_C][i] = xC;

#if p7_DEBUGGING
      if (ox->debugging) p7_omx_DumpFloatRow(ox, TRUE, i, 9, 5, xE, xN, xJ, xB, xC);	/* logify=TRUE, <rowi>=i, width=8, precision=5*/
#endif
    } /* end loop over sequence residues 1..L */

  /* finally C->T, and flip back to log space (nats) */
  /* On overflow, xC is inf or nan (nan arises because inf*0 = nan). */
  /* On an underflow (which shouldn't happen), we counterintuitively return infinity:
   * the effect of this is to force the caller to rescore us with full range.
   */
  if       (isnan(xC))      { *ret_sc = eslINFINITY; return eslERANGE; }
  else if  (xC == 0.0)      { *ret_sc = eslINFINITY; return eslERANGE; } /* underflow "can't happen", actually */
  else if  (isinf(xC) == 1) { *ret_sc = eslINFINITY; return eslERANGE; }

  *ret_sc = log(xC * om->xf[p7O_C][p7O_MOVE]);
  return eslOK;
}

/* Function:  p7_BackwardParser()
 * Synopsis:  Calculates Backward score and X columns in O(M+L) memory.
 * Incept:    SRE, Thu Jul 31 09:29:23 2008 [Janelia]
 *
 * Purpose:   Calculates the Backward score and X columns for sequence
 *            <dsq> of length <L> residues, using optimized profile
 *            <om>, and a preallocated DP matrix <ox>, in linear
 *            memory $O(M+L)$. Return the Backward score (in nats) in
 *            <ret_sc>, and <ox->xmx[][0,1..L]> contain the DP matrix
 *            in single-precision probability for all special X states
 *            (BENCJ).
 *            
 *            The caller must provide a suitably allocated <ox>, with
 *            one DP row to fit <om->M> states, and X beams to fit <L>
 *            residues: for instance by calling <ox = p7_omx_Create(M, 0,
 *            L)> or <p7_omx_GrowTo(ox, M, 0, L)>.
 *            
 *            The Backward score may overflow -- and will, on
 *            high-scoring sequences. Range is limited to -88 to +88
 *            nats (-127 to 127 bits). Scores will not underflow, for
 *            models configured in local mode, within HMMER's design
 *            limits ($L \leq 10^5$; $M \leq 10^4$). On overflow,
 *            <*ret_sc> is <eslINFINITY>.
 *            
 *            The model must be in a local mode; other modes cannot
 *            guarantee that we will not underflow.
 *
 *
 * Args:      dsq     - digital target sequence, 1..L
 *            L       - length of dsq in residues          
 *            om      - optimized profile
 *            ox      - DP matrix
 *            ret_sc  - RETURN: Backward score (in nats)          
 *
 * Returns:   <eslOK> on success; 
 *            <eslERANGE> if the score overflows the limited range of
 *            a probability-space odds ratio; in this case, this is
 *            a high-scoring hit of score > ~128 bits.
 *
 * Throws:    <eslEINVAL> if <ox> allocation is too small, or if the profile
 *            isn't in local alignment mode.
 */
int 
p7_BackwardParser(const ESL_DSQ *dsq, int L, const P7_OPROFILE *om, P7_OMX *ox, float *ret_sc)
{
  register __m128 mpv, ipv, dpv;      /* previous row values                                       */
  register __m128 mcv, dcv;           /* current row values                                        */
  register __m128 tmmv, timv, tdmv;   /* tmp vars for accessing rotated transition scores          */
  register __m128 xBv;		      /* collects B->Mk components of B(i)                         */
  register __m128 xEv;	              /* splatted E(i)                                             */
  __m128   zerov;		      /* splatted 0.0's in a vector                                */
  float    xN, xE, xB, xC, xJ;	      /* special states' scores                                    */
  int      i;			      /* counter over sequence positions 0,1..L                    */
  int      q;			      /* counter over quads 0..Q-1                                 */
  int      Q       = p7O_NQF(om->M);  /* segment length: # of vectors                              */
  int      j;			      /* DD segment iteration counter (4 = full serialization)     */
  __m128  *dp      = ox->dpf[0];      /* using {MDI}MX(q) macro requires initialization of <dp>    */
  __m128  *rp;			      /* will point into om->rf[x] for residue x[i+1]              */
  __m128  *tp;		              /* will point into (and step thru) om->tf transition scores  */

 /* Check that the DP matrix is ok for us. */
  if (Q > ox->allocQ4)                                 ESL_EXCEPTION(eslEINVAL, "DP matrix allocated too small");
  if (ox->allocXRQ*4 <= L)                             ESL_EXCEPTION(eslEINVAL, "DP matrix X beams allocated too small");
  if (om->mode != p7_LOCAL && om->mode != p7_UNILOCAL) ESL_EXCEPTION(eslEINVAL, "This function makes assumptions that only apply to local alignment");
  ox->M  = om->M;
  ox->L  = L;

  /* initialize the L row. */
  xJ = ox->xmx[p7X_J][L] = 0.0;
  xB = ox->xmx[p7X_B][L] = 0.0;
  xN = ox->xmx[p7X_N][L] = 0.0;
  xC = ox->xmx[p7X_C][L] = om->xf[p7O_C][p7O_MOVE];      /* C<-T */
  xE = ox->xmx[p7X_E][L] = xC * om->xf[p7O_E][p7O_MOVE]; /* E<-C, no tail */

  xEv   = _mm_set1_ps(xE);   for (q = 0; q < Q; q++) MMXo(q) = DMXo(q) = xEv;
  zerov = _mm_setzero_ps();  for (q = 0; q < Q; q++) IMXo(q) = zerov;
  dcv   = zerov;		/* solely to silence a compiler warning */

  /* init row L's DD paths, 1) first segment includes xE, from DMXo(q) */
  tp  = om->tf + 8*Q - 1;	/* <*tp> now the [4 8 12 x] TDD quad */
  dpv = esl_sse_leftshift_ps(xEv, zerov);  /* leftshift: [1 5 9 13] becomes [5 9 13 x] with x=0.0 */
  for (q = Q-1; q >= 0; q--)
    {
      dcv    = _mm_mul_ps(dpv, *tp); tp--;
      DMXo(q) = _mm_add_ps(DMXo(q), dcv);
      dpv    = DMXo(q);
    }
  /* 2) three more passes, only extending DD component (dcv only; no xE contrib from DMXo(q)) */
  for (j = 1; j < 4; j++)
    {
      tp  = om->tf + 8*Q - 1;	              /* <*tp> now the [4 8 12 x] TDD quad */
      dcv = esl_sse_leftshift_ps(dcv, zerov); /* [1 5 9 13] -> [5 9 13 x] */
      for (q = Q-1; q >= 0; q--)
	{
	  dcv    = _mm_mul_ps(dcv, *tp); tp--;
	  DMXo(q) = _mm_add_ps(DMXo(q), dcv);
	}
    }
  /* now MD init */
  tp  = om->tf + 7*Q - 3;	              /* <*tp> now the [4 8 12 x] Mk->Dk+1 quad */
  dcv = esl_sse_leftshift_ps(DMXo(0), zerov);  /* [1 5 9 13] -> [5 9 13 x]. */
  for (q = Q-1; q >= 0; q--)
    {
      MMXo(q) = _mm_add_ps(MMXo(q), _mm_mul_ps(dcv, *tp)); tp -= 7;
      dcv    = DMXo(q);
    }

#if p7_DEBUGGING
  if (ox->debugging) p7_omx_DumpFloatRow(ox, TRUE, L, 9, 4, xE, xN, xJ, xB, xC);	/* logify=TRUE, <rowi>=L, width=9, precision=4*/
#endif

  /* main recursion */
  for (i = L-1; i >= 1; i--)	/* backwards stride */
    {
      /* phase 1. B(i) collected. Old row destroyed, new row contains
       *    complete I(i,k), partial {MD}(i,k) w/ no {MD}->{DE} paths yet.
       */
      rp    = om->rf[dsq[i+1]] + 2*Q-1; /* <*rp> is now the [4 8 12 x] insert emission quad */
      tp    = om->tf + 7*Q - 1;	        /* <*tp> is now the [4 8 12 x] TII transition quad  */

      tmmv  = esl_sse_leftshift_ps(om->tf[1], zerov);  	/* because OPROFILE's X->M transition scores are rotated, */
      timv  = esl_sse_leftshift_ps(om->tf[2], zerov);   /* we use tmp variables to access them in stride          */
      tdmv  = esl_sse_leftshift_ps(om->tf[3], zerov);

      mpv = _mm_mul_ps(MMXo(0), om->rf[dsq[i+1]][0]); /* precalc M(i+1,k+1) * e(M_k+1, x_{i+1}) */
      mpv = esl_sse_leftshift_ps(mpv, zerov);
      xBv = zerov;
      for (q = Q-1; q >= 0; q--)     /* backwards stride */
	{
	  ipv = _mm_mul_ps(IMXo(q), *rp);   rp--;  /* precalc I(i+1,k) * e_(I_k, x_{i+1}); i+1's IMXo(q) now free */

	  IMXo(q) = _mm_add_ps(_mm_mul_ps(ipv, *tp), _mm_mul_ps(mpv, timv));   tp--;
	  DMXo(q) =                                  _mm_mul_ps(mpv, tdmv); 
	  mcv    = _mm_add_ps(_mm_mul_ps(ipv, *tp), _mm_mul_ps(mpv, tmmv));   tp-= 2;
	  
	  mpv    = _mm_mul_ps(MMXo(q), *rp);  rp--;  /* obtain mpv for next q. i+1's MMXo(q) is freed  */
	  MMXo(q) = mcv;

	  tdmv   = *tp;   tp--;
	  timv   = *tp;   tp--;
	  tmmv   = *tp;   tp--;

	  xBv  = _mm_add_ps(xBv, _mm_mul_ps(mpv, *tp)); tp--;
	}


      /* phase 2: now that we have accumulated the B->Mk transitions in xBv, we can do the specials */

      /* this incantation is a horiz sum of xBv elements: (_mm_hadd_ps() would require SSE3) */
      xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(0, 3, 2, 1)));
      xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(1, 0, 3, 2)));
      _mm_store_ss(&xB, xBv);

      xC =  xC * om->xf[p7O_C][p7O_LOOP];
      xJ = (xB * om->xf[p7O_J][p7O_MOVE]) + (xJ * om->xf[p7O_J][p7O_LOOP]); /* must come after xB */
      xN = (xB * om->xf[p7O_N][p7O_MOVE]) + (xN * om->xf[p7O_N][p7O_LOOP]); /* must come after xB */
      xE = (xC * om->xf[p7O_E][p7O_MOVE]) + (xJ * om->xf[p7O_E][p7O_LOOP]); /* must come after xJ, xC */

      xEv = _mm_set1_ps(xE);	/* splat */

      /* Stores are separate only for pedagogical reasons: easy to
       * turn this into a more memory efficient version just by
       * deleting the stores.
       */
      ox->xmx[p7X_E][i] = xE;
      ox->xmx[p7X_N][i] = xN;
      ox->xmx[p7X_J][i] = xJ;
      ox->xmx[p7X_B][i] = xB;
      ox->xmx[p7X_C][i] = xC;

      /* phase 3: {MD}->E paths and one step of the D->D paths */
      tp  = om->tf + 8*Q - 1;	/* <*tp> now the [4 8 12 x] TDD quad */
      dpv = _mm_add_ps(DMXo(0), xEv);
      dpv = esl_sse_leftshift_ps(dpv, zerov);                   
      for (q = Q-1; q >= 0; q--)
	{
	  dcv    = _mm_mul_ps(dpv, *tp); tp--;
	  DMXo(q) = _mm_add_ps(DMXo(q), _mm_add_ps(dcv, xEv));
	  dpv    = DMXo(q);
	  MMXo(q) = _mm_add_ps(MMXo(q), xEv);
	}
      
      /* phase 4: finish extending the DD paths */
      /* fully serialized for now */
      for (j = 1; j < 4; j++)	/* three passes: we've already done 1 segment, we need 4 total */
	{
	  dcv = esl_sse_leftshift_ps(dcv, zerov);
	  tp  = om->tf + 8*Q - 1;	/* <*tp> now the [4 8 12 x] TDD quad */
	  for (q = Q-1; q >= 0; q--)
	    {
	      dcv    = _mm_mul_ps(dcv, *tp); tp--;
	      DMXo(q) = _mm_add_ps(DMXo(q), dcv);
	    }
	}

      /* phase 5: add M->D paths */
      dcv = esl_sse_leftshift_ps(DMXo(0), zerov);
      tp  = om->tf + 7*Q - 3;	/* <*tp> is now the [4 8 12 x] Mk->Dk+1 quad */
      for (q = Q-1; q >= 0; q--)
	{
	  MMXo(q) = _mm_add_ps(MMXo(q), _mm_mul_ps(dcv, *tp)); tp -= 7;
	  dcv    = DMXo(q);
	}

#if p7_DEBUGGING
      if (ox->debugging) p7_omx_DumpFloatRow(ox, TRUE, i, 9, 4, xE, xN, xJ, xB, xC);	/* logify=TRUE, <rowi>=i, width=9, precision=4*/
#endif
    } /* thus ends the loop over sequence positions i */

  /* Termination at i=0, where we can only reach N,B states. */
  tp  = om->tf;	        /* <*tp> is now the [1 5 9 13] TBMk transition quad  */
  rp  = om->rf[dsq[1]];	/* <*rp> is now the [1 5 9 13] match emission quad   */
  xBv = zerov;
  for (q = 0; q < Q; q++)
    {
      mpv = _mm_mul_ps(MMXo(q), *rp);  rp += 2;
      mpv = _mm_mul_ps(mpv,    *tp);  tp += 7;
      xBv = _mm_add_ps(xBv,    mpv);
    }
  /* horizontal sum of xBv */
  xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(0, 3, 2, 1)));
  xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(1, 0, 3, 2)));
  _mm_store_ss(&xB, xBv);
  xN = (xB * om->xf[p7O_N][p7O_MOVE]) + (xN * om->xf[p7O_N][p7O_LOOP]); 

  ox->xmx[p7X_B][0] = xB;
  ox->xmx[p7X_C][0] = 0.0;
  ox->xmx[p7X_J][0] = 0.0;
  ox->xmx[p7X_N][0] = xN;
  ox->xmx[p7X_E][0] = 0.0;

#if p7_DEBUGGING    /* Not strictly necessary: */
  for (q = 0; q < Q; q++)
    MMXo(q) = DMXo(q) = IMXo(q) = zerov;
#endif

#if p7_DEBUGGING
  if (ox->debugging) p7_omx_DumpFloatRow(ox, TRUE, 0, 9, 4, ox->xmx[p7X_E][0], ox->xmx[p7X_N][0],  ox->xmx[p7X_J][0], ox->xmx[p7X_B][0],  ox->xmx[p7X_C][0]);	/* logify=TRUE, <rowi>=0, width=9, precision=4*/
#endif

  if       (isnan(xN))      { *ret_sc = eslINFINITY; return eslERANGE; }
  else if  (xN == 0.0)      { *ret_sc = eslINFINITY; return eslERANGE; } /* underflow "can't happen", actually */
  else if  (isinf(xN) == 1) { *ret_sc = eslINFINITY; return eslERANGE; }

  *ret_sc = log(xN);
  return eslOK;
}
/*---------------------- end, parsers ---------------------------*/




/*****************************************************************
 * 2. Benchmark driver.
 *****************************************************************/
#ifdef p7FBPARSERS_BENCHMARK
/* -c, -x options are for debugging and testing: see fwdfilter.c for explanation */
/* 
   gcc -o benchmark-fbparsers -std=gnu99 -g -Wall -msse2 -I.. -L.. -I../../easel -L../../easel -Dp7FBPARSERS_BENCHMARK fbparsers.c -lhmmer -leasel -lm 
   gcc -o benchmark-fbparsers -std=gnu99 -O2 -msse2 -I.. -L.. -I../../easel -L../../easel -Dp7FBPARSERS_BENCHMARK fbparsers.c -lhmmer -leasel -lm 
   icc -o benchmark-fbparsers -O3 -static -I.. -L.. -I../../easel -L../../easel -Dp7FBPARSERS_BENCHMARK fbparsers.c -lhmmer -leasel -lm 

   ./benchmark-fbparsers <hmmfile>           runs benchmark on both Forward and Backward parser
   ./benchmark-fbparsers -b <hmmfile>        gets baseline time to subtract: just random seq generation
   ./benchmark-fbparsers -c -N100 <hmmfile>  compare scores of SSE to generic impl
   ./benchmark-fbparsers -x -N100 <hmmfile>  test that scores match trusted implementation.
 */
#include "p7_config.h"

#include "easel.h"
#include "esl_alphabet.h"
#include "esl_getopts.h"
#include "esl_random.h"
#include "esl_randomseq.h"
#include "esl_stopwatch.h"

#include "hmmer.h"
#include "impl_sse.h"

static ESL_OPTIONS options[] = {
  /* name           type      default  env  range toggles reqs incomp  help                                       docgroup*/
  { "-h",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, NULL, "show brief help on version and usage",             0 },
  { "-b",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, NULL, "baseline timing: don't run DP at all",             0 },
  { "-c",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, "-x", "compare scores to generic implementation (debug)", 0 }, 
  { "-r",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, NULL, "set random number seed randomly",                  0 },
  { "-s",        eslARG_INT,     "42", NULL, NULL,  NULL,  NULL, NULL, "set random number seed to <n>",                    0 },
  { "-x",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, "-c", "equate scores to trusted implementation (debug)",  0 },
  { "-L",        eslARG_INT,    "400", NULL, "n>0", NULL,  NULL, NULL, "length of random target seqs",                     0 },
  { "-N",        eslARG_INT,  "50000", NULL, "n>0", NULL,  NULL, NULL, "number of random target seqs",                     0 },
  { "-F",        eslARG_NONE,   FALSE, NULL, "n>0", NULL,  NULL, "-B", "only benchmark the ForwardParser()",               0 },
  { "-B",        eslARG_NONE,   FALSE, NULL, "n>0", NULL,  NULL, "-B", "only benchmark the BackwardParser()",              0 },
  {  0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
};
static char usage[]  = "[-options] <hmmfile>";
static char banner[] = "benchmark driver for the Parser() implementations";

int 
main(int argc, char **argv)
{
  ESL_GETOPTS    *go      = esl_getopts_CreateDefaultApp(options, 1, argc, argv, banner, usage);
  char           *hmmfile = esl_opt_GetArg(go, 1);
  ESL_STOPWATCH  *w       = esl_stopwatch_Create();
  ESL_RANDOMNESS *r       = NULL;
  ESL_ALPHABET   *abc     = NULL;
  P7_HMMFILE     *hfp     = NULL;
  P7_HMM         *hmm     = NULL;
  P7_BG          *bg      = NULL;
  P7_PROFILE     *gm      = NULL;
  P7_OPROFILE    *om      = NULL;
  P7_GMX         *gx      = NULL;
  P7_OMX         *fwd     = NULL;
  P7_OMX         *bck     = NULL;
  int             L       = esl_opt_GetInteger(go, "-L");
  int             N       = esl_opt_GetInteger(go, "-N");
  ESL_DSQ        *dsq     = malloc(sizeof(ESL_DSQ) * (L+2));
  int             i;
  float           fsc, bsc;
  float           fsc2, bsc2;
  
  p7_FLogsumInit();

  if (esl_opt_GetBoolean(go, "-r"))  r = esl_randomness_CreateTimeseeded();
  else                               r = esl_randomness_Create(esl_opt_GetInteger(go, "-s"));

  if (p7_hmmfile_Open(hmmfile, NULL, &hfp) != eslOK) p7_Fail("Failed to open HMM file %s", hmmfile);
  if (p7_hmmfile_Read(hfp, &abc, &hmm)     != eslOK) p7_Fail("Failed to read HMM");

  bg = p7_bg_Create(abc);
  p7_bg_SetLength(bg, L);
  gm = p7_profile_Create(hmm->M, abc);
  p7_ProfileConfig(hmm, bg, gm, L, p7_LOCAL);
  om = p7_oprofile_Create(gm->M, abc);
  p7_oprofile_Convert(gm, om);
  p7_oprofile_ReconfigLength(om, L);

  if (esl_opt_GetBoolean(go, "-x") && p7_FLogsumError(-0.4, -0.5) > 0.0001)
    p7_Fail("-x here requires p7_Logsum() recompiled in slow exact mode");

  fwd = p7_omx_Create(gm->M, 0, L);
  bck = p7_omx_Create(gm->M, 0, L);
  gx  = p7_gmx_Create(gm->M, L);

  esl_stopwatch_Start(w);
  for (i = 0; i < N; i++)
    {
      esl_rsq_xfIID(r, bg->f, abc->K, L, dsq);
      if (! esl_opt_GetBoolean(go, "-b")) 
	{
	  if (! esl_opt_GetBoolean(go, "-B"))  p7_ForwardParser (dsq, L, om, fwd, &fsc);
	  if (! esl_opt_GetBoolean(go, "-F"))  p7_BackwardParser(dsq, L, om, bck, &bsc);

	  if (esl_opt_GetBoolean(go, "-c") || esl_opt_GetBoolean(go, "-x"))
	    {
	      p7_GForward (dsq, L, gm, gx, &fsc2); 
	      p7_GBackward(dsq, L, gm, gx, &bsc2); 
	      printf("%.4f %.4f %.4f %.4f\n", fsc, bsc, fsc2, bsc2);  
	    }
	}
    }
  esl_stopwatch_Stop(w);
  esl_stopwatch_Display(stdout, w, "# CPU time: ");
  printf("# M    = %d\n",   gm->M);

  free(dsq);
  p7_omx_Destroy(bck);
  p7_omx_Destroy(fwd);
  p7_gmx_Destroy(gx);
  p7_oprofile_Destroy(om);
  p7_profile_Destroy(gm);
  p7_bg_Destroy(bg);
  p7_hmm_Destroy(hmm);
  p7_hmmfile_Close(hfp);
  esl_alphabet_Destroy(abc);
  esl_stopwatch_Destroy(w);
  esl_randomness_Destroy(r);
  esl_getopts_Destroy(go);
  return 0;
}
#endif /*p7FBPARSERS_BENCHMARK*/
/*------------------- end, benchmark driver ---------------------*/

/*****************************************************************
 * 3. Unit tests.
 *****************************************************************/
#ifdef p7FBPARSERS_TESTDRIVE
#include "esl_random.h"
#include "esl_randomseq.h"

/* unit test for scores.
 * compare to GForward() scores and ForwardFilter() scores.
 */
static void
utest_fbparser_scores(ESL_RANDOMNESS *r, ESL_ALPHABET *abc, P7_BG *bg, int M, int L, int N)
{
  char        *msg = "forward/backward parser score unit test failed";
  P7_HMM      *hmm = NULL;
  P7_PROFILE  *gm  = NULL;
  P7_OPROFILE *om  = NULL;
  ESL_DSQ     *dsq = malloc(sizeof(ESL_DSQ) * (L+2));
  P7_OMX      *fwd = p7_omx_Create(M, 0, L);
  P7_OMX      *bck = p7_omx_Create(M, 0, L);
  P7_GMX      *gx  = p7_gmx_Create(M, L);
  float tolerance;
  float fsc1, fsc2, fsc3;
  float bsc1;

  p7_FLogsumInit();
  if (p7_FLogsumError(-0.4, -0.5) > 0.0001) tolerance = 1.0;  /* weaker test against GForward()   */
  else tolerance = 0.0001;   /* stronger test: FLogsum() is in slow exact mode. */

  p7_oprofile_Sample(r, abc, bg, M, L, &hmm, &gm, &om);
  while (N--)
    {
      esl_rsq_xfIID(r, bg->f, abc->K, L, dsq);

      p7_ForwardFilter (dsq, L, om, fwd, &fsc3);
      p7_GForward      (dsq, L, gm, gx,  &fsc2);
      p7_ForwardParser (dsq, L, om, fwd, &fsc1);
      p7_BackwardParser(dsq, L, om, bck, &bsc1);

      /* Forward and Backward parser scores should agree with high tolerance */
      if (fabs(fsc1-bsc1) > 0.0001)    esl_fatal(msg);

      /* they should agree with ForwardFilter with high tolerance */
      if (fabs(fsc1-fsc3) > 0.0001)    esl_fatal(msg);

      /* GForward scores should approximate ForwardParser scores, 
       * with tolerance that depends on how logsum.c was compiled
       */
      if (fabs(fsc1-fsc2) > tolerance) esl_fatal(msg);
    }

  free(dsq);
  p7_hmm_Destroy(hmm);
  p7_omx_Destroy(bck);
  p7_omx_Destroy(fwd);
  p7_gmx_Destroy(gx);
  p7_profile_Destroy(gm);
  p7_oprofile_Destroy(om);
}
#endif /*p7FBPARSERS_TESTDRIVE*/
/*---------------------- end, unit tests ------------------------*/


/*****************************************************************
 * 4. Test driver
 *****************************************************************/
#ifdef p7FBPARSERS_TESTDRIVE
/* 
   gcc -g -Wall -msse2 -std=gnu99 -I.. -L.. -I../../easel -L../../easel -o fbparsers_utest -Dp7FBPARSERS_TESTDRIVE fbparsers.c -lhmmer -leasel -lm
   ./fbparsers_utest
 */
#include "p7_config.h"

#include "easel.h"
#include "esl_alphabet.h"
#include "esl_getopts.h"

#include "hmmer.h"
#include "impl_sse.h"

static ESL_OPTIONS options[] = {
  /* name           type      default  env  range toggles reqs incomp  help                                       docgroup*/
  { "-h",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, NULL, "show brief help on version and usage",           0 },
  { "-r",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, NULL, "set random number seed randomly",                0 },
  { "-s",        eslARG_INT,     "42", NULL, NULL,  NULL,  NULL, NULL, "set random number seed to <n>",                  0 },
  { "-L",        eslARG_INT,    "200", NULL, NULL,  NULL,  NULL, NULL, "size of random sequences to sample",             0 },
  { "-M",        eslARG_INT,    "145", NULL, NULL,  NULL,  NULL, NULL, "size of random models to sample",                0 },
  { "-N",        eslARG_INT,    "100", NULL, NULL,  NULL,  NULL, NULL, "number of random sequences to sample",           0 },
  {  0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
};
static char usage[]  = "[-options]";
static char banner[] = "test driver for the SSE implementation";

int
main(int argc, char **argv)
{
  ESL_GETOPTS    *go   = esl_getopts_CreateDefaultApp(options, 0, argc, argv, banner, usage);
  ESL_RANDOMNESS *r    = NULL;
  ESL_ALPHABET   *abc  = NULL;
  P7_BG          *bg   = NULL;
  int             M    = esl_opt_GetInteger(go, "-M");
  int             L    = esl_opt_GetInteger(go, "-L");
  int             N    = esl_opt_GetInteger(go, "-N");

  if (esl_opt_GetBoolean(go, "-r"))  r = esl_randomness_CreateTimeseeded();
  else                               r = esl_randomness_Create(esl_opt_GetInteger(go, "-s"));

  /* First round of tests for DNA alphabets.  */
  if ((abc = esl_alphabet_Create(eslDNA)) == NULL)  esl_fatal("failed to create alphabet");
  if ((bg = p7_bg_Create(abc))            == NULL)  esl_fatal("failed to create null model");

  utest_fbparser_scores(r, abc, bg, M, L, N);   /* normal sized models */
  utest_fbparser_scores(r, abc, bg, 1, L, 10);  /* size 1 models       */
  utest_fbparser_scores(r, abc, bg, M, 1, 10);  /* size 1 sequences    */

  esl_alphabet_Destroy(abc);
  p7_bg_Destroy(bg);

  /* Second round of tests for amino alphabets.  */
  if ((abc = esl_alphabet_Create(eslAMINO)) == NULL)  esl_fatal("failed to create alphabet");
  if ((bg = p7_bg_Create(abc))              == NULL)  esl_fatal("failed to create null model");

  utest_fbparser_scores(r, abc, bg, M, L, N);   
  utest_fbparser_scores(r, abc, bg, 1, L, 10);  
  utest_fbparser_scores(r, abc, bg, M, 1, 10);  

  esl_alphabet_Destroy(abc);
  p7_bg_Destroy(bg);

  esl_getopts_Destroy(go);
  esl_randomness_Destroy(r);
  return eslOK;
}
#endif /*FBPARSERS_TESTDRIVE*/
/*--------------------- end, test driver ------------------------*/



/*****************************************************************
 * 5. Example
 *****************************************************************/
#ifdef p7FBPARSERS_EXAMPLE
/* Useful for debugging on small HMMs and sequences.
 * 
 * Compares to GForward() and ForwardFilter() scores.
 * 
   gcc -g -Wall -msse2 -std=gnu99 -I.. -L.. -I../../easel -L../../easel -o example -Dp7FBPARSERS_EXAMPLE fbparsers.c -lhmmer -leasel -lm
   ./example <hmmfile> <seqfile>
 */ 
#include "p7_config.h"

#include "easel.h"
#include "esl_alphabet.h"
#include "esl_sq.h"
#include "esl_sqio.h"

#include "hmmer.h"
#include "impl_sse.h"

int 
main(int argc, char **argv)
{
  char           *hmmfile = argv[1];
  char           *seqfile = argv[2];
  ESL_ALPHABET   *abc     = NULL;
  P7_HMMFILE     *hfp     = NULL;
  P7_HMM         *hmm     = NULL;
  P7_BG          *bg      = NULL;
  P7_PROFILE     *gm      = NULL;
  P7_OPROFILE    *om      = NULL;
  P7_GMX         *gx      = NULL;
  P7_OMX         *fwd     = NULL;
  P7_OMX         *bck     = NULL;
  ESL_SQ         *sq      = NULL;
  ESL_SQFILE     *sqfp    = NULL;
  int             format  = eslSQFILE_UNKNOWN;
  float           fsc, bsc;
  int             status;

  /* Read in one HMM */
  if (p7_hmmfile_Open(hmmfile, NULL, &hfp) != eslOK) p7_Fail("Failed to open HMM file %s", hmmfile);
  if (p7_hmmfile_Read(hfp, &abc, &hmm)     != eslOK) p7_Fail("Failed to read HMM");

  /* Read in one sequence */
  sq     = esl_sq_CreateDigital(abc);
  status = esl_sqfile_Open(seqfile, format, NULL, &sqfp);
  if      (status == eslENOTFOUND) p7_Fail("No such file.");
  else if (status == eslEFORMAT)   p7_Fail("Format unrecognized.");
  else if (status == eslEINVAL)    p7_Fail("Can't autodetect stdin or .gz.");
  else if (status != eslOK)        p7_Fail("Open failed, code %d.", status);
  if  (esl_sqio_Read(sqfp, sq) != eslOK) p7_Fail("Failed to read sequence");

  /* create default null model, then create and optimize profile */
  bg = p7_bg_Create(abc);                p7_bg_SetLength(bg, sq->n);
  gm = p7_profile_Create(hmm->M, abc);   p7_ProfileConfig(hmm, bg, gm, sq->n, p7_LOCAL);
  om = p7_oprofile_Create(gm->M, abc);   p7_oprofile_Convert(gm, om);

  /* p7_oprofile_Dump(stdout, om); */

  /* allocate DP matrices for O(M+L) parsers */
  fwd = p7_omx_Create(gm->M, 0, sq->n);
  bck = p7_omx_Create(gm->M, 0, sq->n);

  /* p7_omx_SetDumpMode(stdout, bck, TRUE);  */    /* makes the fast DP algorithms dump their matrices */

  p7_ForwardParser (sq->dsq, sq->n, om, fwd, &fsc);  printf("forward parser:       %.2f nats\n", fsc);
  p7_BackwardParser(sq->dsq, sq->n, om, bck, &bsc);  printf("backward parser:      %.2f nats\n", bsc);

  /* Comparison to other F/B implementations */
  gx  = p7_gmx_Create(gm->M, sq->n);
  p7_GForward     (sq->dsq, sq->n, gm, gx,  &fsc);   printf("GForward:             %.2f nats\n", fsc);
  p7_GBackward    (sq->dsq, sq->n, gm, gx,  &bsc);   printf("GBackward:            %.2f nats\n", bsc);
  /* p7_ForwardFilter(sq->dsq, sq->n, om, fwd, &fsc);   printf("ForwardFilter:        %.2f nats\n", fsc); */

  /* p7_gmx_Dump(stdout, gx); */

  /* In a real app, you'd need to convert raw nat scores to final bit
   * scores, by subtracting the null model score and rescaling.
   */

  /* cleanup */
  esl_sq_Destroy(sq);
  esl_sqfile_Close(sqfp);
  p7_omx_Destroy(bck);
  p7_omx_Destroy(fwd);
  p7_gmx_Destroy(gx);
  p7_oprofile_Destroy(om);
  p7_profile_Destroy(gm);
  p7_bg_Destroy(bg);
  p7_hmm_Destroy(hmm);
  p7_hmmfile_Close(hfp);
  esl_alphabet_Destroy(abc);
  return 0;
}
#endif /*p7IMPL_SSE_EXAMPLE*/

/*****************************************************************
 * @LICENSE@
 *****************************************************************/
