/* SSE implementation of Forward and Backward algorithms.
 *
 * Both profile and DP matrix are striped and interleaved, for fast
 * SIMD vector operations. Calculations are in probability space
 * scaled odds ratios, actually) rather than log probabilities,
 * allowing fast multiply/add operations rather than slow Logsum()
 * calculations. Sparse rescaling is used to achieve full dynamic
 * range of scores.
 * 
 * The p7_Forward() and p7_Backward() routines may be used either in a
 * full O(ML) mode that keeps an entire DP matrix, or in a O(M+L)
 * linear memory "parsing" mode that only keeps one row of memory for
 * the main MDI states and one column 0..L for the special states
 * B,E,N,C,J. Keeping a full matrix allows subsequent stochastic
 * traceback or posterior decoding of any state. In parsing mode, we
 * can do posterior decoding on the special states and determine
 * regions of the target sequence that are generated by the
 * nonhomology states (NCJ) versus not -- thus, identifying where
 * high-probability "regions" are, the first step of identifying the
 * domain structure of a target sequence.
 * 
 * Contents:
 *   1. Forward/Backward implementations.
 *   2. Posterior decoding.
 *   3. Stochastic traceback.
 *   4. Benchmark driver.
 *   5. Unit tests.
 *   6. Test driver.
 *   7. Example.
 *   8. Copyright and license information.
 * 
 * SRE, Thu Jul 31 08:43:20 2008 [Janelia]
 * SVN $Id$
 */
#include "p7_config.h"

#include <stdio.h>
#include <math.h>

#include <xmmintrin.h>		/* SSE  */
#include <emmintrin.h>		/* SSE2 */

#include "easel.h"
#include "esl_sse.h"

#include "hmmer.h"
#include "impl_sse.h"

/*****************************************************************
 * 1. Forward/Backward implementations
 *****************************************************************/

/* Function:  p7_Forward()
 * Synopsis:  The Forward algorithm.
 * Incept:    SRE, Thu Jul 31 09:30:31 2008 [Janelia]
 *
 * Purpose:   Calculates the Forward algorithm for sequence <dsq> of
 *            length <L> residues, using optimized profile <om>, and a
 *            preallocated DP matrix <ox>.  Return the Forward score
 *            (in nats) in <ret_sc>.
 *            
 *            If the <do_full> flag is <TRUE>, then the standard
 *            Forward calculation is done, in $O(ML)$ memory, keeping
 *            the entire DP matrix. The caller must provide a suitably
 *            allocated full <ox> by calling <ox = p7_omx_Create(M, L,
 *            L)> or <p7_omx_GrowTo(ox, M, L, L)>.
 *
 *            If <do_full> is <FALSE>, then a linear-memory "parsing"
 *            calculation is done in $O(M+L)$ memory, keeping only one
 *            row of the main MDI matrix. Upon return,
 *            <ox->xmx[][0,1..L]> contain the DP matrix in
 *            single-precision probability for all special X states
 *            (BENCJ). The caller must provide a suitably allocated
 *            "parsing" <ox> by calling <ox = p7_omx_Create(M, 0, L)>
 *            or <p7_omx_GrowTo(ox, M, 0, L)>.
 *            
 *            The model <om> must be configured in local alignment
 *            mode. The sparse rescaling method used to keep
 *            probability values within single-precision floating
 *            point dynamic range cannot be safely applied to models in
 *            glocal or global mode.
 *
 * Args:      dsq     - digital target sequence, 1..L
 *            L       - length of dsq in residues          
 *            om      - optimized profile
 *            ox      - DP matrix
 *            do_full - TRUE=full matrix; FALSE=linear memory parse mode
 *            ret_sc  - RETURN: Forward score (in nats)          
 *
 * Returns:   <eslOK> on success; 
 *
 * Throws:    <eslEINVAL> if <ox> allocation is too small, or if the profile
 *            isn't in local alignment mode.
 *            <eslERANGE> if the score exceeds the limited range of
 *            a probability-space odds ratio.
 *            In either case, <*opt_sc> is undefined.
 */
int
p7_ForwardParser(const ESL_DSQ *dsq, int L, const P7_OPROFILE *om, P7_OMX *ox, int do_full, float *ret_sc)
{
  register __m128 mpv, dpv, ipv;   /* previous row values                                       */
  register __m128 sv;		   /* temp storage of 1 curr row value in progress              */
  register __m128 dcv;		   /* delayed storage of D(i,q+1)                               */
  register __m128 xEv;		   /* E state: keeps max for Mk->E as we go                     */
  register __m128 xBv;		   /* B state: splatted vector of B[i-1] for B->Mk calculations */
  __m128   zerov;		   /* splatted 0.0's in a vector                                */
  float    xN, xE, xB, xC, xJ;	   /* special states' scores                                    */
  int i;			   /* counter over sequence positions 1..L                      */
  int q;			   /* counter over quads 0..nq-1                                */
  int j;			   /* counter over DD iterations (4 is full serialization)      */
  int Q       = p7O_NQF(om->M);	   /* segment length: # of vectors                              */
  __m128 *dp  = ox->dpf[0];        /* using {MDI}MX(q) macro requires initialization of <dp>    */
  __m128 *rp;			   /* will point at om->rf[x] for residue x[i]                  */
  __m128 *tp;			   /* will point into (and step thru) om->tf                    */

  /* Check that the DP matrix is ok for us. */
  if (Q > ox->allocQ4)                                 ESL_EXCEPTION(eslEINVAL, "DP matrix allocated too small");
  if (ox->allocXRQ*4 <= L)                             ESL_EXCEPTION(eslEINVAL, "DP matrix X beams allocated too small");
  if (om->mode != p7_LOCAL && om->mode != p7_UNILOCAL) ESL_EXCEPTION(eslEINVAL, "Fast filter only works for local alignment");
  ox->M  = om->M;
  ox->L  = L;

  /* Initialization.
   */
  zerov = _mm_setzero_ps();
  for (q = 0; q < Q; q++)
    MMXo(q) = IMXo(q) = DMXo(q) = zerov;
  xE    = ox->xmx[p7X_E][0] = 0.;
  xN    = ox->xmx[p7X_N][0] = 1.;
  xJ    = ox->xmx[p7X_J][0] = 0.;
  xB    = ox->xmx[p7X_B][0] = om->xf[p7O_N][p7O_MOVE];
  xC    = ox->xmx[p7X_C][0] = 0.;

  ox->xmx[p7X_SCALE][0] = 1.0;
  ox->totscale          = 0.0;

#if p7_DEBUGGING
  if (ox->debugging) p7_omx_DumpFloatRow(ox, TRUE, 0, 9, 5, xE, xN, xJ, xB, xC);	/* logify=TRUE, <rowi>=0, width=8, precision=5*/
#endif

  for (i = 1; i <= L; i++)
    {
      dp    = ox->dpf[do_full * i]; /* avoid conditional, use do_full as kronecker delta */
      rp    = om->rf[dsq[i]];
      tp    = om->tf;
      dcv   = _mm_setzero_ps();
      xEv   = _mm_setzero_ps();
      xBv   = _mm_set1_ps(xB);

      /* Right shifts by 4 bytes. 4,8,12,x becomes x,4,8,12.  Shift zeros on. */
      mpv   = esl_sse_rightshift_ps(MMXo(Q-1), zerov);
      dpv   = esl_sse_rightshift_ps(DMXo(Q-1), zerov);
      ipv   = esl_sse_rightshift_ps(IMXo(Q-1), zerov);
      
      for (q = 0; q < Q; q++)
	{
	  /* Calculate new MMXo(i,q); don't store it yet, hold it in sv. */
	  sv   =                _mm_mul_ps(xBv, *tp);  tp++;
	  sv   = _mm_add_ps(sv, _mm_mul_ps(mpv, *tp)); tp++;
	  sv   = _mm_add_ps(sv, _mm_mul_ps(ipv, *tp)); tp++;
	  sv   = _mm_add_ps(sv, _mm_mul_ps(dpv, *tp)); tp++;
	  sv   = _mm_mul_ps(sv, *rp);                  rp++;
	  xEv  = _mm_add_ps(xEv, sv);
	  
	  /* Load {MDI}(i-1,q) into mpv, dpv, ipv;
	   * {MDI}MX(q) is then the current, not the prev row
	   */
	  mpv = MMXo(q);
	  dpv = DMXo(q);
	  ipv = IMXo(q);

	  /* Do the delayed stores of {MD}(i,q) now that memory is usable */
	  MMXo(q) = sv;
	  DMXo(q) = dcv;

	  /* Calculate the next D(i,q+1) partially: M->D only;
           * delay storage, holding it in dcv
	   */
	  dcv   = _mm_mul_ps(sv, *tp); tp++;

	  /* Calculate and store I(i,q) */
	  sv      =                _mm_mul_ps(mpv, *tp);  tp++;
	  sv      = _mm_add_ps(sv, _mm_mul_ps(ipv, *tp)); tp++;
	  IMXo(q) = _mm_mul_ps(sv, *rp);                  rp++;
	}	  

      /* Now the DD paths. We would rather not serialize them but 
       * in an accurate Forward calculation, we have few options.
       */
      /* dcv has carried through from end of q loop above; store it 
       * in first pass, we add M->D and D->D path into DMX
       */
      /* We're almost certainly're obligated to do at least one complete 
       * DD path to be sure: 
       */
      dcv     = esl_sse_rightshift_ps(dcv, zerov);
      DMXo(0) = zerov;
      tp      = om->tf + 7*Q;	/* set tp to start of the DD's */
      for (q = 0; q < Q; q++) 
	{
	  DMXo(q) = _mm_add_ps(dcv, DMXo(q));	
	  dcv     = _mm_mul_ps(DMXo(q), *tp); tp++; /* extend DMXo(q), so we include M->D and D->D paths */
	}

      /* now. on small models, it seems best (empirically) to just go
       * ahead and serialize. on large models, we can do a bit better,
       * by testing for when dcv (DD path) accrued to DMXo(q) is below
       * machine epsilon for all q, in which case we know DMXo(q) are all
       * at their final values. The tradeoff point is (empirically) somewhere around M=100,
       * at least on my desktop. We don't worry about the conditional here;
       * it's outside any inner loops.
       */
      if (om->M < 100)
	{			/* Fully serialized version */
	  for (j = 1; j < 4; j++)
	    {
	      dcv = esl_sse_rightshift_ps(dcv, zerov);
	      tp  = om->tf + 7*Q;	/* set tp to start of the DD's */
	      for (q = 0; q < Q; q++) 
		{ /* note, extend dcv, not DMXo(q); only adding DD paths now */
		  DMXo(q) = _mm_add_ps(dcv, DMXo(q));	
		  dcv     = _mm_mul_ps(dcv, *tp);   tp++; 
		}	    
	    }
	} 
      else
	{			/* Slightly parallelized version, but which incurs some overhead */
	  for (j = 1; j < 4; j++)
	    {
	      register __m128 cv;	/* keeps track of whether any DD's change DMXo(q) */

	      dcv = esl_sse_rightshift_ps(dcv, zerov);
	      tp  = om->tf + 7*Q;	/* set tp to start of the DD's */
	      cv  = zerov;
	      for (q = 0; q < Q; q++) 
		{ /* using cmpgt below tests if DD changed any DMXo(q) *without* conditional branch */
		  sv     = _mm_add_ps(dcv, DMXo(q));	
		  cv     = _mm_or_ps(cv, _mm_cmpgt_ps(sv, DMXo(q))); 
		  DMXo(q) = sv;	                                    /* store new DMXo(q) */
		  dcv    = _mm_mul_ps(dcv, *tp);   tp++;            /* note, extend dcv, not DMXo(q) */
		}	    
	      if (! _mm_movemask_ps(cv)) break; /* DD's didn't change any DMXo(q)? Then done, break out. */
	    }
	}

      /* Add D's to xEv */
      for (q = 0; q < Q; q++) xEv = _mm_add_ps(DMXo(q), xEv);

      /* Finally the "special" states, which start from Mk->E (->C, ->J->B) */
      /* The following incantation is a horizontal sum of xEv's elements  */
      /* These must follow DD calculations, because D's contribute to E in Forward
       * (as opposed to Viterbi)
       */
      xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(0, 3, 2, 1)));
      xEv = _mm_add_ps(xEv, _mm_shuffle_ps(xEv, xEv, _MM_SHUFFLE(1, 0, 3, 2)));
      _mm_store_ss(&xE, xEv);

      xN =  xN * om->xf[p7O_N][p7O_LOOP];
      xC = (xC * om->xf[p7O_C][p7O_LOOP]) +  (xE * om->xf[p7O_E][p7O_MOVE]);
      xJ = (xJ * om->xf[p7O_J][p7O_LOOP]) +  (xE * om->xf[p7O_E][p7O_LOOP]);
      xB = (xJ * om->xf[p7O_J][p7O_MOVE]) +  (xN * om->xf[p7O_N][p7O_MOVE]);
      /* and now xB will carry over into next i, and xC carries over after i=L */

      /* Sparse rescaling.
       * If xE is above threshold, trigger a rescaling event. 
       */
      if (xE > 1.0e4)		/* that's a little less than e^10, ~10% of our dynamic range */
	{
	  xN  = xN / xE;
	  xC  = xC / xE;
	  xJ  = xJ / xE;
	  xB  = xB / xE;
	  xEv = _mm_set1_ps(1.0 / xE);
	  for (q = 0; q < Q; q++)
	    {
	      MMXo(q) = _mm_mul_ps(MMXo(q), xEv);
	      DMXo(q) = _mm_mul_ps(DMXo(q), xEv);
	      IMXo(q) = _mm_mul_ps(IMXo(q), xEv);
	    }
	  ox->xmx[p7X_SCALE][i] = xE;
	  ox->totscale += log(xE);
	  xE = 1.0;		
	}
      else ox->xmx[p7X_SCALE][i] = 1.0;

      /* Storage of the specials.  We could've stored these already
       * but using xE, etc. variables makes it easy to convert this
       * code to O(M) memory versions just by deleting storage steps.
       */
      ox->xmx[p7X_E][i] = xE;
      ox->xmx[p7X_N][i] = xN;
      ox->xmx[p7X_J][i] = xJ;
      ox->xmx[p7X_B][i] = xB;
      ox->xmx[p7X_C][i] = xC;

#if p7_DEBUGGING
      if (ox->debugging) p7_omx_DumpFloatRow(ox, TRUE, i, 9, 5, xE, xN, xJ, xB, xC);	/* logify=TRUE, <rowi>=i, width=8, precision=5*/
#endif
    } /* end loop over sequence residues 1..L */

  /* finally C->T, and flip total score back to log space (nats) */
  /* On overflow, xC is inf or nan (nan arises because inf*0 = nan). */
  /* On an underflow (which shouldn't happen), we counterintuitively return infinity:
   * the effect of this is to force the caller to rescore us with full range.
   */
  if       (isnan(xC))      ESL_EXCEPTION(eslERANGE, "forward score is NaN");
  else if  (xC == 0.0)      ESL_EXCEPTION(eslERANGE, "forward score underflow (is 0.0)");
  else if  (isinf(xC) == 1) ESL_EXCEPTION(eslERANGE, "forward score overflow (is infinity)");

  *ret_sc = ox->totscale + log(xC * om->xf[p7O_C][p7O_MOVE]);
  return eslOK;
}



/* Function:  p7_Backward()
 * Synopsis:  The Backward algorithm.
 * Incept:    SRE, Thu Jul 31 09:29:23 2008 [Janelia]
 *
 * Purpose:   Calculates the Backward algorithm for sequence <dsq> of
 *            length <L> residues, using optimized profile <om>, and a
 *            preallocated DP matrix <ox>. Optionally return the
 *            Backward score (in nats) in <opt_sc>.
 *            
 *            If the <do_full> flag is <TRUE>, then the standard
 *            Backward calculation is done, in $O(ML)$ memory, keeping
 *            the entire DP matrix. The caller must provide a suitably
 *            allocated full <ox> by calling <ox = p7_omx_Create(M, L,
 *            L)> or <p7_omx_GrowTo(ox, M, L, L)>.
 *
 *            If <do_full> is <FALSE>, then a linear-memory "parsing"
 *            calculation is done in $O(M+L)$ memory, keeping only one
 *            row of the main MDI matrix. Upon return,
 *            <ox->xmx[][0,1..L]> contain the DP matrix in
 *            single-precision probability for all special X states
 *            (BENCJ). The caller must provide a suitably allocated
 *            "parsing" <ox> by calling <ox = p7_omx_Create(M, 0, L)>
 *            or <p7_omx_GrowTo(ox, M, 0, L)>.
 *            
 *            The model <om> must be configured in local alignment
 *            mode. The sparse rescaling method used to keep
 *            probability values within single-precision floating
 *            point dynamic range cannot be safely applied to models in
 *            glocal or global mode.
 *
 * Args:      dsq     - digital target sequence, 1..L
 *            L       - length of dsq in residues          
 *            om      - optimized profile
 *            ox      - DP matrix
 *            do_full - TRUE=full matrix; FALSE=linear memory parse mode
 *            opt_sc  - optRETURN: Backward score (in nats)          
 *
 * Returns:   <eslOK> on success. 
 *
 * Throws:    <eslEINVAL> if <ox> allocation is too small, or if the profile
 *            isn't in local alignment mode.
 *            <eslERANGE> if the score exceeds the limited range of
 *            a probability-space odds ratio.
 *            In either case, <*opt_sc> is undefined.
 */
int 
p7_BackwardParser(const ESL_DSQ *dsq, int L, const P7_OPROFILE *om, const P7_OMX *fwd, 
		  P7_OMX *bck, float *opt_sc)
{
  register __m128 mpv, ipv, dpv;      /* previous row values                                       */
  register __m128 mcv, dcv;           /* current row values                                        */
  register __m128 tmmv, timv, tdmv;   /* tmp vars for accessing rotated transition scores          */
  register __m128 xBv;		      /* collects B->Mk components of B(i)                         */
  register __m128 xEv;	              /* splatted E(i)                                             */
  __m128   zerov;		      /* splatted 0.0's in a vector                                */
  float    xN, xE, xB, xC, xJ;	      /* special states' scores                                    */
  int      i;			      /* counter over sequence positions 0,1..L                    */
  int      q;			      /* counter over quads 0..Q-1                                 */
  int      Q       = p7O_NQF(om->M);  /* segment length: # of vectors                              */
  int      j;			      /* DD segment iteration counter (4 = full serialization)     */
  __m128  *dp;                        /* using {MDI}MX(q) macro requires initialization of <dp>    */
  __m128  *rp;			      /* will point into om->rf[x] for residue x[i+1]              */
  __m128  *tp;		              /* will point into (and step thru) om->tf transition scores  */

 /* Check that the DP matrix is ok for us. */
  if (Q > bck->allocQ4)  
    ESL_EXCEPTION(eslEINVAL, "DP matrix allocated too small");
  if (bck->allocXRQ*4 <= L) 
    ESL_EXCEPTION(eslEINVAL, "DP matrix X beams allocated too small");
  if (om->mode != p7_LOCAL && om->mode != p7_UNILOCAL)
    ESL_EXCEPTION(eslEINVAL, "This function makes assumptions that only apply to local alignment");
  bck->M  = om->M;
  bck->L  = L;

  /* initialize the L row. */
  dp = bck->dpf[L * do_full];
  xJ = 0.0;
  xB = 0.0;
  xN = 0.0;
  xC = om->xf[p7O_C][p7O_MOVE];      /* C<-T */
  xE = xC * om->xf[p7O_E][p7O_MOVE]; /* E<-C, no tail */

  xEv   = _mm_set1_ps(xE);   for (q = 0; q < Q; q++) MMXo(q) = DMXo(q) = xEv;
  zerov = _mm_setzero_ps();  for (q = 0; q < Q; q++) IMXo(q) = zerov;
  dcv   = zerov;		/* solely to silence a compiler warning */

  /* init row L's DD paths, 1) first segment includes xE, from DMXo(q) */
  tp  = om->tf + 8*Q - 1;	/* <*tp> now the [4 8 12 x] TDD quad */
  dpv = _mm_move_ss(DMXo(Q-1), zerov);                  /* start leftshift: [1 5 9 13] -> [x 5 9 13] */
  dpv = _mm_shuffle_ps(dpv, dpv, _MM_SHUFFLE(0,3,2,1)); /* finish leftshift:[x 5 9 13] -> [5 9 13 x] */
  for (q = Q-1; q >= 0; q--)
    {
      dcv     = _mm_mul_ps(dpv, *tp);      tp--;
      DMXo(q) = _mm_add_ps(DMXo(q), dcv);
      dpv     = DMXo(q);
    }
  /* 2) three more passes, only extending DD component (dcv only; no xE contrib from DMXo(q)) */
  for (j = 1; j < 4; j++)
    {
      tp  = om->tf + 8*Q - 1;	              /* <*tp> now the [4 8 12 x] TDD quad */
      dcv = _mm_move_ss(dcv, zerov);                        /* start leftshift: [1 5 9 13] -> [x 5 9 13] */
      dcv = _mm_shuffle_ps(dcv, dcv, _MM_SHUFFLE(0,3,2,1)); /* finish leftshift:[x 5 9 13] -> [5 9 13 x] */
      for (q = Q-1; q >= 0; q--)
	{
	  dcv     = _mm_mul_ps(dcv, *tp); tp--;
	  DMXo(q) = _mm_add_ps(DMXo(q), dcv);
	}
    }
  /* now MD init */
  tp  = om->tf + 7*Q - 3;	              /* <*tp> now the [4 8 12 x] Mk->Dk+1 quad */
  dcv = _mm_move_ss(DMXo(0), zerov);                    /* start leftshift: [1 5 9 13] -> [x 5 9 13] */
  dcv = _mm_shuffle_ps(dcv, dcv, _MM_SHUFFLE(0,3,2,1)); /* finish leftshift:[x 5 9 13] -> [5 9 13 x] */
  for (q = Q-1; q >= 0; q--)
    {
      MMXo(q) = _mm_add_ps(MMXo(q), _mm_mul_ps(dcv, *tp)); tp -= 7;
      dcv     = DMXo(q);
    }

  /* Sparse rescaling: same scale factors as fwd matrix */
  if (fwd->xmx[p7X_SCALE][L] > 1.0)
    {
      xN  = xN / fwd->xmx[p7X_SCALE][L];
      xC  = xC / fwd->xmx[p7X_SCALE][L];
      xJ  = xJ / fwd->xmx[p7X_SCALE][L];
      xB  = xB / fwd->xmx[p7X_SCALE][L];
      xEv = _mm_set1_ps(1.0 / fwd->xmx[p7X_SCALE][L]);
      for (q = 0; q < Q; q++) {
	MMXo(q) = _mm_mul_ps(MMXo(q), xEv);
	DMXo(q) = _mm_mul_ps(DMXo(q), xEv);
	IMXo(q) = _mm_mul_ps(IMXo(q), xEv);
      }
      xE = 1.0;
    }
  bck->xmx[p7X_SCALE][L] = fwd->xmx[p7X_SCALE][L];

  /* Stores */
  bck->xmx[p7X_E][L] = xE;
  bck->xmx[p7X_N][L] = xN;
  bck->xmx[p7X_J][L] = xJ;
  bck->xmx[p7X_B][L] = xB;
  bck->xmx[p7X_C][L] = xC;

#if p7_DEBUGGING
  if (bck->debugging) p7_omx_DumpFloatRow(bck, TRUE, L, 9, 4, xE, xN, xJ, xB, xC);	/* logify=TRUE, <rowi>=L, width=9, precision=4*/
#endif

  /* main recursion */
  for (i = L-1; i >= 1; i--)	/* backwards stride */
    {
      /* phase 1. B(i) collected. Old row destroyed, new row contains
       *    complete I(i,k), partial {MD}(i,k) w/ no {MD}->{DE} paths yet.
       */
      dp = bck->dpf[i * do_full];
      rp = om->rf[dsq[i+1]] + 2*Q-1; /* <*rp> is now the [4 8 12 x] insert emission quad */
      tp = om->tf + 7*Q - 1;	        /* <*tp> is now the [4 8 12 x] TII transition quad  */

      /* leftshift the first transition quads */
      tmmv = _mm_move_ss(om->tf[1], zerov); tmmv = _mm_shuffle_ps(tmmv, tmmv, _MM_SHUFFLE(0,3,2,1));
      timv = _mm_move_ss(om->tf[2], zerov); timv = _mm_shuffle_ps(timv, timv, _MM_SHUFFLE(0,3,2,1));
      tdmv = _mm_move_ss(om->tf[3], zerov); tdmv = _mm_shuffle_ps(tdmv, tdmv, _MM_SHUFFLE(0,3,2,1));

      mpv = _mm_mul_ps(MMXo(0), om->rf[dsq[i+1]][0]); /* precalc M(i+1,k+1) * e(M_k+1, x_{i+1}) */
      mpv = _mm_move_ss(mpv, zerov);
      mpv = _mm_shuffle_ps(mpv, mpv, _MM_SHUFFLE(0,3,2,1));

      xBv = zerov;
      for (q = Q-1; q >= 0; q--)     /* backwards stride */
	{
	  ipv = _mm_mul_ps(IMXo(q), *rp);   rp--;  /* precalc I(i+1,k) * e_(I_k, x_{i+1}); i+1's IMXo(q) now free */

	  IMXo(q) = _mm_add_ps(_mm_mul_ps(ipv, *tp), _mm_mul_ps(mpv, timv));   tp--;
	  DMXo(q) =                                  _mm_mul_ps(mpv, tdmv); 
	  mcv    = _mm_add_ps(_mm_mul_ps(ipv, *tp), _mm_mul_ps(mpv, tmmv));   tp-= 2;
	  
	  mpv    = _mm_mul_ps(MMXo(q), *rp);  rp--;  /* obtain mpv for next q. i+1's MMXo(q) is freed  */
	  MMXo(q) = mcv;

	  tdmv   = *tp;   tp--;
	  timv   = *tp;   tp--;
	  tmmv   = *tp;   tp--;

	  xBv  = _mm_add_ps(xBv, _mm_mul_ps(mpv, *tp)); tp--;
	}

      /* phase 2: now that we have accumulated the B->Mk transitions in xBv, we can do the specials */
      /* this incantation is a horiz sum of xBv elements: (_mm_hadd_ps() would require SSE3) */
      xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(0, 3, 2, 1)));
      xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(1, 0, 3, 2)));
      _mm_store_ss(&xB, xBv);

      xC =  xC * om->xf[p7O_C][p7O_LOOP];
      xJ = (xB * om->xf[p7O_J][p7O_MOVE]) + (xJ * om->xf[p7O_J][p7O_LOOP]); /* must come after xB */
      xN = (xB * om->xf[p7O_N][p7O_MOVE]) + (xN * om->xf[p7O_N][p7O_LOOP]); /* must come after xB */
      xE = (xC * om->xf[p7O_E][p7O_MOVE]) + (xJ * om->xf[p7O_E][p7O_LOOP]); /* must come after xJ, xC */
      xEv = _mm_set1_ps(xE);	/* splat */


      /* phase 3: {MD}->E paths and one step of the D->D paths */
      tp  = om->tf + 8*Q - 1;	/* <*tp> now the [4 8 12 x] TDD quad */
      dpv = _mm_add_ps(DMXo(0), xEv);
      dpv = _mm_move_ss(dpv, zerov);
      dpv = _mm_shuffle_ps(dpv, dpv, _MM_SHUFFLE(0,3,2,1));
      for (q = Q-1; q >= 0; q--)
	{
	  dcv    = _mm_mul_ps(dpv, *tp); tp--;
	  DMXo(q) = _mm_add_ps(DMXo(q), _mm_add_ps(dcv, xEv));
	  dpv    = DMXo(q);
	  MMXo(q) = _mm_add_ps(MMXo(q), xEv);
	}
      
      /* phase 4: finish extending the DD paths */
      /* fully serialized for now */
      for (j = 1; j < 4; j++)	/* three passes: we've already done 1 segment, we need 4 total */
	{
	  dcv = _mm_move_ss(dcv, zerov);
	  dcv = _mm_shuffle_ps(dcv, dcv, _MM_SHUFFLE(0,3,2,1));
	  tp  = om->tf + 8*Q - 1;	/* <*tp> now the [4 8 12 x] TDD quad */
	  for (q = Q-1; q >= 0; q--)
	    {
	      dcv    = _mm_mul_ps(dcv, *tp); tp--;
	      DMXo(q) = _mm_add_ps(DMXo(q), dcv);
	    }
	}

      /* phase 5: add M->D paths */
      dcv = _mm_move_ss(DMXo(0), zerov);
      dcv = _mm_shuffle_ps(dcv, dcv, _MM_SHUFFLE(0,3,2,1));
      tp  = om->tf + 7*Q - 3;	/* <*tp> is now the [4 8 12 x] Mk->Dk+1 quad */
      for (q = Q-1; q >= 0; q--)
	{
	  MMXo(q) = _mm_add_ps(MMXo(q), _mm_mul_ps(dcv, *tp)); tp -= 7;
	  dcv    = DMXo(q);
	}

      /* Sparse rescaling: same scale factors as fwd matrix */
      if (fwd->xmx[p7X_SCALE][i] > 1.0)
	{
	  xE  = xE / fwd->xmx[p7X_SCALE][i];
	  xN  = xN / fwd->xmx[p7X_SCALE][i];
	  xC  = xC / fwd->xmx[p7X_SCALE][i];
	  xJ  = xJ / fwd->xmx[p7X_SCALE][i];
	  xB  = xB / fwd->xmx[p7X_SCALE][i];
	  xEv = _mm_set1_ps(1.0 / fwd->xmx[p7X_SCALE][i]);
	  for (q = 0; q < Q; q++) {
	    MMXo(q) = _mm_mul_ps(MMXo(q), xEv);
	    DMXo(q) = _mm_mul_ps(DMXo(q), xEv);
	    IMXo(q) = _mm_mul_ps(IMXo(q), xEv);
	  }

	}
      bck->xmx[p7X_SCALE][i] = fwd->xmx[p7X_SCALE][i];

      /* Stores are separate only for pedagogical reasons: easy to
       * turn this into a more memory efficient version just by
       * deleting the stores.
       */
      bck->xmx[p7X_E][i] = xE;
      bck->xmx[p7X_N][i] = xN;
      bck->xmx[p7X_J][i] = xJ;
      bck->xmx[p7X_B][i] = xB;
      bck->xmx[p7X_C][i] = xC;

#if p7_DEBUGGING
      if (bck->debugging) p7_omx_DumpFloatRow(bck, TRUE, i, 9, 4, xE, xN, xJ, xB, xC);	/* logify=TRUE, <rowi>=i, width=9, precision=4*/
#endif
    } /* thus ends the loop over sequence positions i */

  /* Termination at i=0, where we can only reach N,B states. */
  dp  = ox->dpf[0];
  tp  = om->tf;	        /* <*tp> is now the [1 5 9 13] TBMk transition quad  */
  rp  = om->rf[dsq[1]];	/* <*rp> is now the [1 5 9 13] match emission quad   */
  xBv = zerov;
  for (q = 0; q < Q; q++)
    {
      mpv = _mm_mul_ps(MMXo(q), *rp);  rp += 2;
      mpv = _mm_mul_ps(mpv,     *tp);  tp += 7;
      xBv = _mm_add_ps(xBv,     mpv);
    }
  /* horizontal sum of xBv */
  xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(0, 3, 2, 1)));
  xBv = _mm_add_ps(xBv, _mm_shuffle_ps(xBv, xBv, _MM_SHUFFLE(1, 0, 3, 2)));
  _mm_store_ss(&xB, xBv);
 
  xN = (xB * om->xf[p7O_N][p7O_MOVE]) + (xN * om->xf[p7O_N][p7O_LOOP]);  

  bck->xmx[p7X_B][0] = xB;
  bck->xmx[p7X_C][0] = 0.0;
  bck->xmx[p7X_J][0] = 0.0;
  bck->xmx[p7X_N][0] = xN;
  bck->xmx[p7X_E][0] = 0.0;

  bck->xmx[p7X_SCALE][0] = fwd->xmx[p7X_SCALE][0]; /* 1.0 */
  bck->totscale          = fwd->totscale;

#if p7_DEBUGGING
  for (q = 0; q < Q; q++) /* Not strictly necessary: */
    MMXo(q) = DMXo(q) = IMXo(q) = zerov;
  if (bck->debugging) p7_omx_DumpFloatRow(bck, TRUE, 0, 9, 4, bck->xmx[p7X_E][0], bck->xmx[p7X_N][0],  bck->xmx[p7X_J][0], bck->xmx[p7X_B][0],  bck->xmx[p7X_C][0]);	/* logify=TRUE, <rowi>=0, width=9, precision=4*/
#endif

  if       (isnan(xN))      ESL_EXCEPTION(eslERANGE, "forward score is NaN");
  else if  (xN == 0.0)      ESL_EXCEPTION(eslERANGE, "forward score underflow (is 0.0)");
  else if  (isinf(xN) == 1) ESL_EXCEPTION(eslERANGE, "forward score overflow (is infinity)");

  if (opt_sc != NULL) *opt_sc = bck->totscale + log(xN);
  return eslOK;
}
/*---------------------- end, forward/backward ---------------------------*/


/*****************************************************************
 * 2. Posterior decoding.
 *****************************************************************/


/* Function:  p7_PosteriorDecoding()
 * Synopsis:  Posterior decoding of residue assignment.
 * Incept:    SRE, Fri Aug  8 14:29:42 2008 [UA217 to SFO]
 *
 * Purpose:   Calculates a posterior decoding of the residues <1..L> in
 *            a target sequence of length <L>, given profile <om>, a
 *            filled Forward matrix <oxf>, and a Backward matrix <oxb>.
 *            
 *            The resulting posterior decoding is stored in a DP matrix <pp>,
 *            provided by the caller.
 *            
 *            Each residue <i> must have been emitted by match state
 *            <1..M>, insert state <1..M-1>, or an NN, CC, or JJ loop
 *            transition.  For <dp = pp->dp>, <xmx = pp->xmx>,
 *            <MMXo(i,k)> is the probability that match <k> emitted
 *            residue <i>; <IMXo(i,k)> is the probability that insert
 *            <k> emitted residue <i>; <pp->xmx[NCJ][i]> are
 *            the probabilities that residue <i> was
 *            emitted on an NN, CC, or JJ transition. The sum over all
 *            these possibilities for a given residue <i> is 1.0.
 *            
 *            The caller may pass the Backward matrix <oxb> as <pp>,
 *            in which case <bck> will be overwritten with
 *            <pp>. However, the caller may \emph{not} overwrite <fwd>
 *            this way; an <(i-1)> dependency in the calculation of
 *            NN, CC, JJ transitions prevents this.
 *
 * Args:      L    - length of the target sequence
 *            om   - profile (must be the same that was used to fill <oxf>, <oxb>).
 *            oxf  - filled Forward matrix 
 *            oxb  - filled Backward matrix
 *            pp   - RESULT: posterior decoding matrix.
 *
 * Returns:   <eslOK> on success.
 *
 * Throws:    (no abnormal error conditions)
 */
int
p7_PosteriorDecoding(const P7_PROFILE *om, const P7_OMX *oxf, P7_OMX *oxb, P7_OMX *pp)
{
  register __m128 *ppv;
  register __m128 *fv;
  register __m128 *bv;
  register __m128  totrv;
  register __m128  scv;
  int    L  = oxf->L;
  int    M  = om->M;
  int    Q3 = 3*p7O_NQF(M);	/* 3, for MDI */
  int    i,q;
  float  totp_reciprocal = 1.0 / (oxf->xmx[p7X_C][L] * om->xf[p7O_C][p7O_MOVE]);

  ppv = pp->dpf[0];
  for (q = 0; q < Q3; q++) 
    ppv[q] = _mm_setzero_ps();

  totrv = _mm_set1_ps(totp_reciprocal);
  for (i = 1; i <= L; i++)
    {
      ppv =  pp->dpf[i];
      fv  = oxf->dpf[i]
      bv  = oxb->dpf[i];
      scv = _mm_set1_ps(oxf->xmx[p7X_SCALE][i]);

      for (q = 0; q < Q3; q++)
	{
	  ppv[q] = _mm_mul_ps(fv[q],  bv[q]);
	  ppv[q] = _mm_mul_ps(ppv[q], scv);
	  ppv[q] = _mm_mul_ps(ppv[q], totrv);
	}

      pp->xmx[p7X_N][i] = oxf->xmx[p7X_N][i-1] * oxb->xmx[p7X_N][i] * om->xf[p7O_N][p7O_LOOP] * totp_reciprocal;
      pp->xmx[p7X_J][i] = oxf->xmx[p7X_J][i-1] * oxb->xmx[p7X_J][i] * om->xf[p7O_J][p7O_LOOP] * totp_reciprocal;
      pp->xmx[p7X_C][i] = oxf->xmx[p7X_C][i-1] * oxb->xmx[p7X_C][i] * om->xf[p7O_C][p7O_LOOP] * totp_reciprocal;
    }
  return eslOK;
}

/* Function:  p7_omx_DomainDecoding()
 * Synopsis:  Posterior decoding of domain location.
 * Incept:    SRE, Tue Aug  5 08:39:07 2008 [Janelia]
 *
 * Purpose:   
 *
 * Args:      
 *
 * Returns:   
 *
 * Throws:    (no abnormal error conditions)
 *
 * Xref:      
 */
int
p7_omx_DomainPosteriors(P7_OPROFILE *om, P7_OMX *oxf, P7_OMX *oxb, P7_DOMAINDEF *ddef)
{
  int   L               = oxf->L;
  float totp_reciprocal = 1.0 / (oxf->xmx[p7X_C][L] * om->xf[p7O_C][p7O_MOVE]);
  float njcp;
  int   i;

  ddef->btot[0] = 0.0;
  ddef->etot[0] = 0.0;
  ddef->mocc[0] = 0.0;
  for (i = 1; i <= L; i++)
    {
      ddef->btot[i] = ddef->btot[i-1] +
	(oxf->xmx[p7X_B][i-1] * oxb->xmx[p7X_B][i-1] * oxf->xmx[p7X_SCALE][i-1] * totp_reciprocal);
      ddef->etot[i] = ddef->etot[i-1] +
	(oxf->xmx[p7X_E][i]   * oxb->xmx[p7X_E][i]   * oxf->xmx[p7X_SCALE][i]   * totp_reciprocal);

      njcp  = oxf->xmx[p7X_N][i-1] * oxb->xmx[p7X_N][i] * om->xf[p7O_N][p7O_LOOP] * totp_reciprocal;
      njcp += oxf->xmx[p7X_J][i-1] * oxb->xmx[p7X_J][i] * om->xf[p7O_J][p7O_LOOP] * totp_reciprocal;
      njcp += oxf->xmx[p7X_C][i-1] * oxb->xmx[p7X_C][i] * om->xf[p7O_C][p7O_LOOP] * totp_reciprocal;
      ddef->mocc[i] = 1. - njcp;
    }
  ddef->L = oxf->L;
  return eslOK;
}
/*------------------ end, posterior decoding --------------------*/


/*****************************************************************
 * 3. Stochastic traceback
 *****************************************************************/ 

/* Function:  p7_StochasticTrace()
 * Synopsis:  Sample a traceback from a Forward matrix
 * Incept:    SRE, Fri Aug  8 17:40:18 2008 [UA217, IAD-SFO]
 *
 * Purpose:   Perform a stochastic traceback from Forward matrix <ox>,
 *            using random number generator <r>, in order to sample an
 *            alignmnet of model <om> to digital sequence <dsq> of
 *            length <L>. 
 *            
 *            The sampled traceback is returned in <tr>, which the
 *            caller provides with at least an initial allocation;
 *            the <tr> allocation will be grown as needed here.
 *
 * Args:      r   - source of random numbers
 *            dsq - digital sequence being aligned, 1..L
 *            L   - length of dsq
 *            om  - profile
 *            ox  - Forward matrix to trace, LxM
 *            tr  - storage for the recovered traceback
 *
 * Returns:   <eslOK> on success
 *
 * Throws:    <eslEMEM> on allocation error.
 */
int
p7_StochasticTrace(ESL_RANDOMNESS *r, const ESL_DSQ *dsq, int L, const P7_OPROFILE *om, const P7_OMX *ox,
		   P7_TRACE *tr)
{
  int i;			/* position in sequence 1..L */
  int k;			/* position in model 1..M */
  int status;			

  
  /* Initialization.
   * (back to front. ReverseTrace() called later.)
   */
  if ((status = p7_trace_Append(tr, p7T_T, 0, 0)) != eslOK) return status;
  if ((status = p7_trace_Append(tr, p7T_C, 0, 0)) != eslOK) return status;
  i    = L;			/* next position to explain in seq */

  while (tr->st[tr->N-1] != p7T_S)
    {

      /* SRE STOPPED HERE */
    }

  if ((status = p7_trace_Reverse(tr)) != eslOK) return status;
  return eslOK;
}
/*------------------ end, stochastic traceback ------------------*/


/*****************************************************************
 * 4. Benchmark driver.
 *****************************************************************/
#ifdef p7FBPARSERS_BENCHMARK
/* -c, -x options are for debugging and testing: see fwdfilter.c for explanation */
/* 
   gcc -o benchmark-fbparsers -std=gnu99 -g -Wall -msse2 -I.. -L.. -I../../easel -L../../easel -Dp7FBPARSERS_BENCHMARK fbparsers.c -lhmmer -leasel -lm 
   gcc -o benchmark-fbparsers -std=gnu99 -O2 -msse2 -I.. -L.. -I../../easel -L../../easel -Dp7FBPARSERS_BENCHMARK fbparsers.c -lhmmer -leasel -lm 
   icc -o benchmark-fbparsers -O3 -static -I.. -L.. -I../../easel -L../../easel -Dp7FBPARSERS_BENCHMARK fbparsers.c -lhmmer -leasel -lm 

   ./benchmark-fbparsers <hmmfile>           runs benchmark on both Forward and Backward parser
   ./benchmark-fbparsers -c -N100 <hmmfile>  compare scores of SSE to generic impl
   ./benchmark-fbparsers -x -N100 <hmmfile>  test that scores match trusted implementation.
 */
#include "p7_config.h"

#include "easel.h"
#include "esl_alphabet.h"
#include "esl_getopts.h"
#include "esl_random.h"
#include "esl_randomseq.h"
#include "esl_stopwatch.h"

#include "hmmer.h"
#include "impl_sse.h"

static ESL_OPTIONS options[] = {
  /* name           type      default  env  range toggles reqs incomp  help                                       docgroup*/
  { "-h",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, NULL, "show brief help on version and usage",             0 },
  { "-c",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, "-x", "compare scores to generic implementation (debug)", 0 }, 
  { "-r",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, NULL, "set random number seed randomly",                  0 },
  { "-s",        eslARG_INT,     "42", NULL, NULL,  NULL,  NULL, NULL, "set random number seed to <n>",                    0 },
  { "-x",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, "-c", "equate scores to trusted implementation (debug)",  0 },
  { "-L",        eslARG_INT,    "400", NULL, "n>0", NULL,  NULL, NULL, "length of random target seqs",                     0 },
  { "-N",        eslARG_INT,  "50000", NULL, "n>0", NULL,  NULL, NULL, "number of random target seqs",                     0 },
  { "-F",        eslARG_NONE,   FALSE, NULL, "n>0", NULL,  NULL, "-B", "only benchmark the ForwardParser()",               0 },
  { "-B",        eslARG_NONE,   FALSE, NULL, "n>0", NULL,  NULL, "-B", "only benchmark the BackwardParser()",              0 },
  {  0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
};
static char usage[]  = "[-options] <hmmfile>";
static char banner[] = "benchmark driver for the Parser() implementations";

int 
main(int argc, char **argv)
{
  ESL_GETOPTS    *go      = esl_getopts_CreateDefaultApp(options, 1, argc, argv, banner, usage);
  char           *hmmfile = esl_opt_GetArg(go, 1);
  ESL_STOPWATCH  *w       = esl_stopwatch_Create();
  ESL_RANDOMNESS *r       = NULL;
  ESL_ALPHABET   *abc     = NULL;
  P7_HMMFILE     *hfp     = NULL;
  P7_HMM         *hmm     = NULL;
  P7_BG          *bg      = NULL;
  P7_PROFILE     *gm      = NULL;
  P7_OPROFILE    *om      = NULL;
  P7_GMX         *gx      = NULL;
  P7_OMX         *fwd     = NULL;
  P7_OMX         *bck     = NULL;
  int             L       = esl_opt_GetInteger(go, "-L");
  int             N       = esl_opt_GetInteger(go, "-N");
  ESL_DSQ        *dsq     = malloc(sizeof(ESL_DSQ) * (L+2));
  int             i;
  float           fsc, bsc;
  float           fsc2, bsc2;
  double          base_time, bench_time, Mcs;

  p7_FLogsumInit();

  if (esl_opt_GetBoolean(go, "-r"))  r = esl_randomness_CreateTimeseeded();
  else                               r = esl_randomness_Create(esl_opt_GetInteger(go, "-s"));

  if (p7_hmmfile_Open(hmmfile, NULL, &hfp) != eslOK) p7_Fail("Failed to open HMM file %s", hmmfile);
  if (p7_hmmfile_Read(hfp, &abc, &hmm)     != eslOK) p7_Fail("Failed to read HMM");

  bg = p7_bg_Create(abc);
  p7_bg_SetLength(bg, L);
  gm = p7_profile_Create(hmm->M, abc);
  p7_ProfileConfig(hmm, bg, gm, L, p7_LOCAL);
  om = p7_oprofile_Create(gm->M, abc);
  p7_oprofile_Convert(gm, om);
  p7_oprofile_ReconfigLength(om, L);

  if (esl_opt_GetBoolean(go, "-x") && p7_FLogsumError(-0.4, -0.5) > 0.0001)
    p7_Fail("-x here requires p7_Logsum() recompiled in slow exact mode");

  fwd = p7_omx_Create(gm->M, 0, L);
  bck = p7_omx_Create(gm->M, 0, L);
  gx  = p7_gmx_Create(gm->M, L);

  /* Get a baseline time: how long it takes just to generate the sequences */
  esl_stopwatch_Start(w);
  for (i = 0; i < N; i++)
    esl_rsq_xfIID(r, bg->f, abc->K, L, dsq);
  esl_stopwatch_Stop(w);
  base_time = w->user;

  esl_stopwatch_Start(w);
  for (i = 0; i < N; i++)
    {
      esl_rsq_xfIID(r, bg->f, abc->K, L, dsq);
      if (! esl_opt_GetBoolean(go, "-B"))  p7_ForwardParser (dsq, L, om,      fwd, &fsc);
      if (! esl_opt_GetBoolean(go, "-F"))  p7_BackwardParser(dsq, L, om, fwd, bck, &bsc);

      if (esl_opt_GetBoolean(go, "-c") || esl_opt_GetBoolean(go, "-x"))
	{
	  p7_GForward (dsq, L, gm, gx, &fsc2); 
	  p7_GBackward(dsq, L, gm, gx, &bsc2); 
	  printf("%.4f %.4f %.4f %.4f\n", fsc, bsc, fsc2, bsc2);  
	}
    }
  esl_stopwatch_Stop(w);
  bench_time = w->user - base_time;
  Mcs        = (double) N * (double) L * (double) gm->M * 1e-6 / (double) bench_time;
  esl_stopwatch_Display(stdout, w, "# CPU time: ");
  printf("# M    = %d\n",   gm->M);
  printf("# %.1f Mc/s\n", Mcs);

  free(dsq);
  p7_omx_Destroy(bck);
  p7_omx_Destroy(fwd);
  p7_gmx_Destroy(gx);
  p7_oprofile_Destroy(om);
  p7_profile_Destroy(gm);
  p7_bg_Destroy(bg);
  p7_hmm_Destroy(hmm);
  p7_hmmfile_Close(hfp);
  esl_alphabet_Destroy(abc);
  esl_stopwatch_Destroy(w);
  esl_randomness_Destroy(r);
  esl_getopts_Destroy(go);
  return 0;
}
#endif /*p7FBPARSERS_BENCHMARK*/
/*------------------- end, benchmark driver ---------------------*/

/*****************************************************************
 * 3. Unit tests.
 *****************************************************************/
#ifdef p7FBPARSERS_TESTDRIVE
#include "esl_random.h"
#include "esl_randomseq.h"

/* unit test for scores.
 * compare to GForward() scores and ForwardFilter() scores.
 */
static void
utest_fbparser_scores(ESL_RANDOMNESS *r, ESL_ALPHABET *abc, P7_BG *bg, int M, int L, int N)
{
  char        *msg = "forward/backward parser score unit test failed";
  P7_HMM      *hmm = NULL;
  P7_PROFILE  *gm  = NULL;
  P7_OPROFILE *om  = NULL;
  ESL_DSQ     *dsq = malloc(sizeof(ESL_DSQ) * (L+2));
  P7_OMX      *fwd = p7_omx_Create(M, 0, L);
  P7_OMX      *bck = p7_omx_Create(M, 0, L);
  P7_GMX      *gx  = p7_gmx_Create(M, L);
  float tolerance;
  float fsc1, fsc2, fsc3;
  float bsc1;

  p7_FLogsumInit();
  if (p7_FLogsumError(-0.4, -0.5) > 0.0001) tolerance = 1.0;  /* weaker test against GForward()   */
  else tolerance = 0.0001;   /* stronger test: FLogsum() is in slow exact mode. */

  p7_oprofile_Sample(r, abc, bg, M, L, &hmm, &gm, &om);
  while (N--)
    {
      esl_rsq_xfIID(r, bg->f, abc->K, L, dsq);

      p7_ForwardFilter (dsq, L, om, fwd, &fsc3);
      p7_GForward      (dsq, L, gm, gx,  &fsc2);
      p7_ForwardParser (dsq, L, om,      fwd, &fsc1);
      p7_BackwardParser(dsq, L, om, fwd, bck, &bsc1);

      /* Forward and Backward parser scores should agree with high tolerance */
      if (fabs(fsc1-bsc1) > 0.0001)    esl_fatal(msg);

      /* they should agree with ForwardFilter with high tolerance */
      if (fabs(fsc1-fsc3) > 0.0001)    esl_fatal(msg);

      /* GForward scores should approximate ForwardParser scores, 
       * with tolerance that depends on how logsum.c was compiled
       */
      if (fabs(fsc1-fsc2) > tolerance) esl_fatal(msg);
    }

  free(dsq);
  p7_hmm_Destroy(hmm);
  p7_omx_Destroy(bck);
  p7_omx_Destroy(fwd);
  p7_gmx_Destroy(gx);
  p7_profile_Destroy(gm);
  p7_oprofile_Destroy(om);
}
#endif /*p7FBPARSERS_TESTDRIVE*/
/*---------------------- end, unit tests ------------------------*/


/*****************************************************************
 * 4. Test driver
 *****************************************************************/
#ifdef p7FBPARSERS_TESTDRIVE
/* 
   gcc -g -Wall -msse2 -std=gnu99 -I.. -L.. -I../../easel -L../../easel -o fbparsers_utest -Dp7FBPARSERS_TESTDRIVE fbparsers.c -lhmmer -leasel -lm
   ./fbparsers_utest
 */
#include "p7_config.h"

#include "easel.h"
#include "esl_alphabet.h"
#include "esl_getopts.h"

#include "hmmer.h"
#include "impl_sse.h"

static ESL_OPTIONS options[] = {
  /* name           type      default  env  range toggles reqs incomp  help                                       docgroup*/
  { "-h",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, NULL, "show brief help on version and usage",           0 },
  { "-r",        eslARG_NONE,   FALSE, NULL, NULL,  NULL,  NULL, NULL, "set random number seed randomly",                0 },
  { "-s",        eslARG_INT,     "42", NULL, NULL,  NULL,  NULL, NULL, "set random number seed to <n>",                  0 },
  { "-L",        eslARG_INT,    "200", NULL, NULL,  NULL,  NULL, NULL, "size of random sequences to sample",             0 },
  { "-M",        eslARG_INT,    "145", NULL, NULL,  NULL,  NULL, NULL, "size of random models to sample",                0 },
  { "-N",        eslARG_INT,    "100", NULL, NULL,  NULL,  NULL, NULL, "number of random sequences to sample",           0 },
  {  0, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
};
static char usage[]  = "[-options]";
static char banner[] = "test driver for the SSE implementation";

int
main(int argc, char **argv)
{
  ESL_GETOPTS    *go   = esl_getopts_CreateDefaultApp(options, 0, argc, argv, banner, usage);
  ESL_RANDOMNESS *r    = NULL;
  ESL_ALPHABET   *abc  = NULL;
  P7_BG          *bg   = NULL;
  int             M    = esl_opt_GetInteger(go, "-M");
  int             L    = esl_opt_GetInteger(go, "-L");
  int             N    = esl_opt_GetInteger(go, "-N");

  if (esl_opt_GetBoolean(go, "-r"))  r = esl_randomness_CreateTimeseeded();
  else                               r = esl_randomness_Create(esl_opt_GetInteger(go, "-s"));

  /* First round of tests for DNA alphabets.  */
  if ((abc = esl_alphabet_Create(eslDNA)) == NULL)  esl_fatal("failed to create alphabet");
  if ((bg = p7_bg_Create(abc))            == NULL)  esl_fatal("failed to create null model");

  utest_fbparser_scores(r, abc, bg, M, L, N);   /* normal sized models */
  utest_fbparser_scores(r, abc, bg, 1, L, 10);  /* size 1 models       */
  utest_fbparser_scores(r, abc, bg, M, 1, 10);  /* size 1 sequences    */

  esl_alphabet_Destroy(abc);
  p7_bg_Destroy(bg);

  /* Second round of tests for amino alphabets.  */
  if ((abc = esl_alphabet_Create(eslAMINO)) == NULL)  esl_fatal("failed to create alphabet");
  if ((bg = p7_bg_Create(abc))              == NULL)  esl_fatal("failed to create null model");

  utest_fbparser_scores(r, abc, bg, M, L, N);   
  utest_fbparser_scores(r, abc, bg, 1, L, 10);  
  utest_fbparser_scores(r, abc, bg, M, 1, 10);  

  esl_alphabet_Destroy(abc);
  p7_bg_Destroy(bg);

  esl_getopts_Destroy(go);
  esl_randomness_Destroy(r);
  return eslOK;
}
#endif /*FBPARSERS_TESTDRIVE*/
/*--------------------- end, test driver ------------------------*/



/*****************************************************************
 * 5. Example
 *****************************************************************/
#ifdef p7FBPARSERS_EXAMPLE
/* Useful for debugging on small HMMs and sequences.
 * 
 * Compares to GForward() and ForwardFilter() scores.
 * 
   gcc -g -Wall -msse2 -std=gnu99 -I.. -L.. -I../../easel -L../../easel -o example -Dp7FBPARSERS_EXAMPLE fbparsers.c -lhmmer -leasel -lm
   ./example <hmmfile> <seqfile>
 */ 
#include "p7_config.h"

#include "easel.h"
#include "esl_alphabet.h"
#include "esl_sq.h"
#include "esl_sqio.h"

#include "hmmer.h"
#include "impl_sse.h"

int 
main(int argc, char **argv)
{
  char           *hmmfile = argv[1];
  char           *seqfile = argv[2];
  ESL_ALPHABET   *abc     = NULL;
  P7_HMMFILE     *hfp     = NULL;
  P7_HMM         *hmm     = NULL;
  P7_BG          *bg      = NULL;
  P7_PROFILE     *gm      = NULL;
  P7_OPROFILE    *om      = NULL;
  P7_GMX         *gx      = NULL;
  P7_OMX         *fwd     = NULL;
  P7_OMX         *bck     = NULL;
  ESL_SQ         *sq      = NULL;
  ESL_SQFILE     *sqfp    = NULL;
  int             format  = eslSQFILE_UNKNOWN;
  float           fsc, bsc;
  int             status;

  /* Read in one HMM */
  if (p7_hmmfile_Open(hmmfile, NULL, &hfp) != eslOK) p7_Fail("Failed to open HMM file %s", hmmfile);
  if (p7_hmmfile_Read(hfp, &abc, &hmm)     != eslOK) p7_Fail("Failed to read HMM");

  /* Read in one sequence */
  sq     = esl_sq_CreateDigital(abc);
  status = esl_sqfile_Open(seqfile, format, NULL, &sqfp);
  if      (status == eslENOTFOUND) p7_Fail("No such file.");
  else if (status == eslEFORMAT)   p7_Fail("Format unrecognized.");
  else if (status == eslEINVAL)    p7_Fail("Can't autodetect stdin or .gz.");
  else if (status != eslOK)        p7_Fail("Open failed, code %d.", status);
  if  (esl_sqio_Read(sqfp, sq) != eslOK) p7_Fail("Failed to read sequence");

  /* create default null model, then create and optimize profile */
  bg = p7_bg_Create(abc);                p7_bg_SetLength(bg, sq->n);
  gm = p7_profile_Create(hmm->M, abc);   p7_ProfileConfig(hmm, bg, gm, sq->n, p7_LOCAL);
  om = p7_oprofile_Create(gm->M, abc);   p7_oprofile_Convert(gm, om);

  /* p7_oprofile_Dump(stdout, om); */

  /* allocate DP matrices for O(M+L) parsers */
  fwd = p7_omx_Create(gm->M, 0, sq->n);
  bck = p7_omx_Create(gm->M, 0, sq->n);

  /* p7_omx_SetDumpMode(stdout, bck, TRUE);  */    /* makes the fast DP algorithms dump their matrices */

  p7_ForwardParser (sq->dsq, sq->n, om,      fwd, &fsc);  printf("forward parser:       %.2f nats\n", fsc);
  p7_BackwardParser(sq->dsq, sq->n, om, fwd, bck, &bsc);  printf("backward parser:      %.2f nats\n", bsc);

  /* Comparison to other F/B implementations */
  gx  = p7_gmx_Create(gm->M, sq->n);
  p7_GForward     (sq->dsq, sq->n, gm, gx,  &fsc);   printf("GForward:             %.2f nats\n", fsc);
  p7_GBackward    (sq->dsq, sq->n, gm, gx,  &bsc);   printf("GBackward:            %.2f nats\n", bsc);
  /* p7_ForwardFilter(sq->dsq, sq->n, om, fwd, &fsc);   printf("ForwardFilter:        %.2f nats\n", fsc); */

  /* p7_gmx_Dump(stdout, gx); */

  /* In a real app, you'd need to convert raw nat scores to final bit
   * scores, by subtracting the null model score and rescaling.
   */

  /* cleanup */
  esl_sq_Destroy(sq);
  esl_sqfile_Close(sqfp);
  p7_omx_Destroy(bck);
  p7_omx_Destroy(fwd);
  p7_gmx_Destroy(gx);
  p7_oprofile_Destroy(om);
  p7_profile_Destroy(gm);
  p7_bg_Destroy(bg);
  p7_hmm_Destroy(hmm);
  p7_hmmfile_Close(hfp);
  esl_alphabet_Destroy(abc);
  return 0;
}
#endif /*p7IMPL_SSE_EXAMPLE*/

/*****************************************************************
 * @LICENSE@
 *****************************************************************/
