.TH "hmmindex" 1 "@RELEASEDATE@" "@PACKAGE@ @RELEASE@" "@PACKAGE@ Manual"

.SH NAME
.TP 
hmmindex - create a binary SSI index for an HMM database

.SH SYNOPSIS
.B hmmindex
.I [options]
.I database

.SH DESCRIPTION

.B hmmindex
is a utility that creates a binary SSI ("squid sequence index"
format) index for an HMM database file called
.I database.
The new index file is named
.IR database.ssi.
An SSI index file is required for 
.B hmmfetch
to work, and also for the PVM implementation of 
.B hmmpfam.

.SH OPTIONS

.TP
.B -h
Print brief help; includes version number and summary of
all options, including expert options.


