/* version.h -- automatically generated by a Makefile. DO NOT EDIT. */
#define PACKAGE     "HMMER"
#define RELEASE     "2.2h"
#define RELEASEDATE "January 2003"
#define COPYRIGHT   "Copyright (C) 1992-2003 HHMI/Washington University School of Medicine"
#define LICENSE     "Freely distributed under the GNU General Public License (GPL)"
