/* version.h -- automatically generated by a Makefile. DO NOT EDIT. */
#define PACKAGE     "HMMER"
#define RELEASE     "2.1.3"
#define RELEASEDATE "December 1999"
#define COPYRIGHT   "Copyright (C) 1992-2000 Washington University School of Medicine"
#define LICENSE     "Freely distributed under the GNU General Public License (GPL)"
