MODULE = misc

LIBOBJS =  emit.o\
	   h2_io.o\
	   logsum.o\
	   p7_trace_metrics.o\
	   tracealign.o

LIBHDRS =  

OBJS =

HDRS =

PROGS =

UTESTS =  emit_utest \
	  logsum_utest \
	  p7_trace_metrics_utest

STATS  =  emit_stats

BENCHMARKS =  logsum_benchmark

EXAMPLES = emit_example \
	   logsum_example \
	   p7_trace_metrics_example \
	   tracealign_example

LIBTMP =

top_srcdir   = ../..
top_builddir = ../..
srcdir       = .

SHELL        = /bin/sh

include ../Makefile-subdirs.mk

################################################################
# @LICENSE@
#
# SVN $URL$
# SVN $Id$
################################################################

